
* Javascript
** Javascript notes
file:javascript.org
** JQuery
* CSS
** 选择器
1. 选择器大全, http://www.w3cschool.cc/cssref/css-selectors.html
*** 类选择器
: h1.article-title {xxx:xxx;xxx:xxx;}
: <h1 class='article-title'>xxx</h1>
一个元素也可以应用多个类的样式
: <h1 class='article-title emph'>xxx</h1>
多个类的样式属于平级，谁的样式覆盖谁，只看样式的加载顺序。
*** 后代选择器
: p.nav a {...}
表明p.nav内的所有a元素。

和子元素选择器有何区别？
: p.nav>a {...}
表明p.nav内的子元素a. 子元素选择器选择的元素可能少于后代选择器.
** CSS属性参考手册
1. http://www.w3school.com.cn/css/index.asp
** 特殊属性说明
*** display
display: inline-block
行内块元素, CSS 2.1之后支持.
和 inline 有何分别?

display: list-item
将作为列表项显示.

*** font-weight
value: normal | bold | bolder | lighter
也可以用数字: 100, 200, 300, 400, 500, 600, 700, 800, 900
由细到粗，其中400表示normal.

** 技巧
*** 禁止元素选中:
http://stackoverflow.com/questions/826782/css-rule-to-disable-text-selection-highlighting

#+BEGIN_SRC css
.noselect {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
#+END_SRC

#+BEGIN_SRC html
<p>
  Selectable text.
</p>
<p class="noselect">
  Unselectable text.
</p>
#+END_SRC

也可以使用js:
#+BEGIN_SRC js
function makeUnselectable(node) {
    if (node.nodeType == 1) {
        node.setAttribute("unselectable", "on");
    }
    var child = node.firstChild;
    while (child) {
        makeUnselectable(child);
        child = child.nextSibling;
    }
}

makeUnselectable(document.getElementById("foo"));
#+END_SRC
*** 给文字增加模糊阴影
text-shadow, CSS 3新特性.
: text-shadow: h-shadow v-shadow [blur] [color]
- h-shadow是阴影的横向位移，可以为负值
- v-shadow是阴影的纵向位移，可以为负值
- blur 阴影边缘模糊的距离，（让阴影和背景柔和地过度）
- color 阴影的颜色.

如带黑色阴影的白色文本。
#+BEGIN_SRC css
color:white;
text-shadow:2px 2px 4px #000000;
#+END_SRC

*** CSS动画
1. css动画简介 http://www.ruanyifeng.com/blog/2014/02/css_transition_and_animation.html
*** 按钮样式
1. 怎么做类似github的按钮? http://code.ciaoca.com/style/css3-github-btn/, source: https://github.com/necolas/css3-github-buttons/blob/master/gh-buttons.css

* HTML
** HTML header
** HTML5
HTML5 中的一些有趣的新特性：

- 用于绘画的 canvas 元素
- 用于媒介回放的 video 和 audio 元素
- 对本地离线存储的更好的支持
- 新的特殊内容元素，比如 article、footer、header、nav、section
- 新的表单控件，比如 calendar、date、time、email、url、search

现代的浏览器都支持 HTML5。

* PHP

* Design
1. http://www.csdn.net/article/2013-07-17/2816256-whats-new-for-designers
** How to Setup a website
source: http://stackoverflow.com/questions/3292866/web-project-planning-tutorial

1. Read [[http://programmers.stackexchange.com/questions/46716/what-technical-details-should-a-programmer-of-a-web-application-consider-before][What should a developer know before building a public web site?]]
2. Define and document scope
3. Define and document functional requirements
4. Look for existing solutions - if you can leverage a CMS or eCommerce package you can save a lot of development time
5. Design database (ER Diagram)
6. Design website structure (sections, links, navigation)
7. Design page layout - wireframe tools or even paper/pencil are useful for this
8. Design application structure - high level class structure
9. Identify libraries and frameworks, e.g., Doctrine, Zend, CodeIgnitor, etc
10. Technical design decisions - naming conventions, logging strategy, exception handling
11. Testing Plan
12. Implementation Plan

PHP project planning for idiots
PHP Application Development (part 1 and part 2)
Web Application Development - A Guide to Success
StackOverflow
How to plan my web based project before starting code ?
Web Design Process - Planning Stage…
How to design/plan for web application development?
Planning web applications
http://stackoverflow.com/search?q=[web-development]+plan
shareedit
answered Nov 3 '10 at 22:34

BenV
3,74231442

** Responsive Design
1. 阮一峰的日志: http://www.ruanyifeng.com/blog/2012/05/responsive_web_design.html
2. 外国网站: http://zurb.com/university/responsive-design

* Tools
2. http://jsfiddle.net, Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.
* 美工
** 为什么要切片
为了图片快速下载和显示。
** PS切片工具具体使用
Link: http://jingyan.baidu.com/article/25648fc1c3eaee9190fd0059.html
** 开源切片方案
ImageMagick
: convert -crop 200 +repage verybig.jpg slice%02d.jpg

GIMP
1. 从选区建立参考线，然后 滤镜 | Web | slice，会生成html的table布局。http://docs.gimp.org/en/python-fu-slice.html
2. webSplit插件 http://www.arakne.es/en/dessign/gimp-websplit-new-version/, 通过路径建立切片，生成div布局。如何使用websplit: http://tieba.baidu.com/p/3238938081
