好买基金网: http://www.howbuy.com/

基金学院. http://www.howbuy.com/fundcollege/

基金再买入称为 *基金补仓*.

- 货币型/理财型，随时补仓，可定投.
- 债券型，择时补仓，择优补仓.

任何补仓，都应建立在你看好该基金未来还有上升空间的基础之上。
1）当大盘处于下跌途中，可以在大盘差不多调整到位开始向上反转时进行补仓。比如持有的基金是投资大盘蓝筹股的，就关注上证指数，在大盘差不多调整到位时，进行补仓。如果持有的基金是投资创业板的，就关注创业板指数。
2）当大盘处于上涨阶段，且之后上涨概率较大，那么越早补仓越好。当上涨一段时间达到你的预设收益目标，就要见好就收、落袋为安。（参考：卖还是不卖？什么时候赎回基金合适？）
3）当市场时涨时跌处于震荡时，定投对投资者进行补仓会就会起到很大帮助。因为其摊低成本、熨平基金净值波动的功能，会减少投资者在补仓中的不安情绪，待市场上涨时使投资者获取更大的收益。（了解定投详情>>）

还是利用好买基金网的“自选基金”工具，对比大盘指数、自选基金的实时涨跌情况，可以在估值在相对低位时进行补仓。（如何利用基金估值买基金？）

投资者在进行补仓时，要重点关注基金产品的以往业绩，分析基金产品的未来收益，要选择那些历史业绩优异且具有良好成长性的基金产品。

股票基金怎么选: http://www.howbuy.com/fundcollege/news/2015-03-20/3087306.html

** 我的投资理财类书单（2017版）

为什么要整理这份书单？因为我发现，通过整理在某个领域的书单，可以清楚自己的知识体系，知道自己落入什么流派，知道自己在什么位置。
清楚了这些之后，可以明确自己的发展方向，进一步选择适合自己的书来读。因此这书单是需要经常整理和更新的。

*入门与发心*

1. 《富爸爸穷爸爸》，投资的启蒙书。读的时候还很懵懂，也没有做好投资的准备，找时间再读一遍。
2. 《小狗钱钱》，投资启蒙书，很棒，以后一定要让我的孩子读。读完之后开始投资基金，从货币基金起步。
3. 《财务自由之路》，德国畅销书，对于股票和基金的投资方法流于泛泛，主要是我也缺乏长期持有的决心。
4. 《从零开始学炒股》，挺不错的入门书，从基本概念讲起。
5. 柯蒂斯·费思《海龟交易法则》。没有读完，读后感是：遵守纪律，坚持一个有效的方法，就会有收益。

*趋势投机*

1. 尼古拉.达拉斯《我如何从股市赚了200万》，箱体方法，跟定上升趋势的股票。我认为这本书是趋势交易的经典，不用任何指标，只要有K线就够了。这本书我评5星。只是要想达到作者的修为，需要极大的定力和耐心。
2. 乔·洛氏《洛氏霍克交易法》，对我很有启发的书，怎么确认趋势？怎么看出趋势的反转？读这本书之前，我只关心k线的实体，读过此书后，我开始关心k线的最高点和最低点，以及k线的位置。低位123、高位123、洛氏霍克点。同样是裸K战法，不需要指标。这本书我评5星。
3. 缠中说禅《教你炒股票108课》。这是国内最有影响力的分析价格运动的著作。但容易让人缠在里面走不出来。我也被缠了1年。现在主要用缠论来分析走势。尽管这本书未能让我稳定盈利，我还是评级为5星。
4. 陈秋明《图解缠论：核心理论推导与实战演示》。我读的第一本缠论书。这本书撇开笔、线段划分等细节，直接讲走势动力学。作为缠论入门，也不错。我评级为4星。
5. 付学军编《教你炒股票之缠论新解》。《教你炒股票108课》是缠中说禅陆续发表在新浪博客上的，内容比较散乱。这本书是编者根据自己的理解出的整理版，我评级为3星。
6. 比尔·威廉姆斯博士《混沌操作法》。据说缠论的很多思想借鉴了这本书，像分型、走势动力等。因为这本书借助鳄鱼线（类似均线）来持股，所以归为趋势投机。还没读完，有时间重读一遍。评4星。
7. 黄圣根《期货投资的艺术——在不确定性中寻找确定性》。虽然是国人写的，但作者是实干出来的，写的也很实在，和林辉太郎先生的思想一样：猜行情方向并不重要，重要的是交易技巧。还在阅读中，评4星吧。
8. 托马斯·卡尔博士《以趋势交易为生》。老外写的书，适合新手，里面介绍了各种指标、均线、趋势线这些烂大街的技术。不过容易误导读者，过分依赖指标，会被指标玩死。这本书我评3星。
9. 亚历山大·埃尔德。《以交易为生》，作者是为了躲避斯大林的统治，逃到美国的俄罗斯人。里面提到了怎么划趋势线，主张趋势线应该通过密集成交区。也提到很多指标，其中指出，rsi上也可以划趋势线，我原来还以为这么划趋势线是我独创的呢。和《以趋势交易为生》的内容差不多，我同样评3星。
10. 科林·亚历山大《股票市场的时机选择》，还没读完，和上面两本的思想应该大同小异。找时间读完。评3星。
11. 威廉·欧奈尔《笑傲股市》。作者提出CANSLIM选股公式，并依据茶杯柄形态捕捉牛股。虽然别人评价很高，但对我帮助不大。评3星。
12. 鹿希武《趋势交易法》，生搬硬套波浪理论，有点事后诸葛亮的感觉，如果是实盘操作，恐怕分析不了那么准吧。再说划趋势线，本来就是主观的方法，用来参考的，作者却有点教条主义。评2星。
13. 《短线王国——炒股稳定获利法》，讲了波段操作的低买高卖时机。没有独创的思想，只是把常用的短线方法总结了一下。评2星。
14. 《我如何以交易为生》，一个实战家，但是他不看图表，用的指标我也无法借鉴，所以只是翻读。不读也罢。我评1星。
15. 王宁《暴力K线擒大牛》。没什么用，不读也罢。评1星。
16. 黑马王子《量柱擒涨停》。天量柱、地量柱、倍量柱等，黄金柱、将军柱什么的，看起来很有道理，但实战很难应用。作者是个骗子，这本书我评0星，认为是垃圾书。


*波动投机（赚取波动差价）*

1. 林辉太郎《期货市场的技术》，虽然老人家写作缺少章法，有点罗嗦，但是让人眼前一亮。“不猜行情，专注交易的技术”，分批操作，K线的节奏，对我启发最大。评5星。
2. 林辉太郎《职业炒手的核心技术秘密》。老人家的书都很好读，因为写的都很浅，很实在。这本书可以和《期货市场的技术》互为补充，同样评5星。
3. 立花义正《你也可以成为股票操作高手》，立花在工作中出了事故被截肢，从那之后在家炒股，并烤炒股过上了富裕的生活。他是林辉太郎的朋友，也是林辉太郎写书采访的对象。和林辉太郎一样，他主张分批买入和反向建仓。评4星。
4. 林辉太郎《波段交易法》。这本书写得挺罗嗦，而且核心思想很简单，一般日本股票是以3个月的节奏波动，即三个月上涨，三个月下跌，因此投资者可以专注一个波动节奏比较标准的股票，以三个月为周期反复交易。用A股的股票来验证这个结论，该结论站不住，但同样给我启发。我喜欢的持股周期是一个月，我发现通过股票的60分钟线段通常延续1个月的时间居多，这样我月初选股的时候就可以选刚开始走60分钟上升线段的股票。该书评3星。
12. 严为民《吾股丰登》。虽然骂作者的较多，我觉得这本书还是比较真诚的。不过读不读皆可，评2星。

*基金、定投、低风险*

1. 季凯帆《解读基金》，如何选基金，如何配置基金组合，如何定投。作者说一辈子长期持有，我不赞同，牛市行情快走完的时候，就该出来，然后再开始新一轮定投。或者像台湾定投教母说的，每次定投的收益达到30%的时候，就全部卖出，然后开始新的定投循环。这叫做及时止盈获利。
2. 银行螺丝钉《指数基金投资指南》。上雪球之后，发现了这本书。作为资产配置的一部分，我开始定投指数基金。以后基金以指数基金和红利基金为主，比较省心，不用关心是否换基金经理。
3. 《低风险投资之路》。作者好像是雪球上的David吧。还没读完，有时间通读一遍，多学点武艺。
4.《网格交易法》，此法思想简单，容易上手。适用于震荡行情，资金效率不高。关键是省心，但也需要耐心。

*价值投资*

1. 徐茂华《我做散户这十年——三万赚到千万》。炒股经历分享，有读网络小说的爽感。作者擅长选股之后捂到爆发，归为价投吧。
2. 刘宏《5000到350万炒股手记》，同上，被股市打败的时候，可以看看鼓舞士气。
3. 格雷厄姆《聪明的投资者》。价投的经典书籍，准备读。
4. 邱国鹭《投资中最简单的事》。准备读。
5.《人人都看得懂的财报书》。其实我很不喜欢做财报分析的工作，因为不会。至今看基本面也就是看看市盈率、市净率、净资产收益率、每股收益、每年分红情况。以后有时间还是读一下吧。

*总结*

投资这件事，跟性格关系很大，别人的方法照抄不来的。某本书只能给自己启发，但最终的交易系统是靠自己摸索出来的。
在价投方面还是一片空白，目前个人性格还是喜欢投机。
不过加入雪球后，陆续把一些好股加入了自选，把基本面差的都踢出了自选。
虽然不了解企业估值，但从球友那学习，我把一些公认的低价好股加入了自选并开始交易：比如中国建筑、葛洲坝、中南建设、国投电力、长江电力、伊利股份等。

我目前的流派是趋势选股，波动投机，滚动操作。需要加强的是波段持股能力。
以后希望的发展方向是交易型价值投资。选定好股票，建立一定数量的底仓，然后为了乐趣，做一些降低成本的投机操作。

2017-10-11 Wed
** 小散的进化轨迹（2017年10月）
不足：
1. 对下降趋势的个股重仓，搏反弹，没有及时减仓，导致浮亏扩大。比如金牛化工和中色股份。
2. 不愿对个股认输，对于有了浮亏的个股不愿清仓，一定要扭亏为盈才清仓。这其实丧失的是机会成本，把资金放在向下走的个股里，和把资金放在向上走的个股里，哪个挣钱快？我这种心态很奇怪，就像明明和一个女人在一起不愉快，非要纠缠，直到她说自己好才愿意放她走。

收获：
1. 读了《证券交易新空间》，学习了混沌操作法2。混沌操作法的买点很多，包括5类：鳄鱼线、分形突破、AO三类买点（可以用MACD红绿柱子代替）、AC、平衡线。总的来说，这是个趋势交易法，抓到一个好的趋势，一直跟到尾。遇到震荡行情，容易反复止损。当然，通过鳄鱼线的过滤，会把很多假的分形突破排除在外。混沌操作法2和洛氏霍克交易法很像，分形也类似于RH点，这两者可以结合起来确认趋势。手里又多了一件判断趋势的武器。
2. 敢于买突破了。以前总是不敢买突破，怕被套在高处站岗。但西方交易法都是教我们买突破。离底部较近的放量突破一定要敢于买。月末的白云机场、东百集团、三一重工、中国建筑都是追着突破买的。要想不错过买点就得突破和回调互相结合。
3. 放弃缠论操盘。本月上旬，想把缠论和我的K线节奏买入法结合起来，比如缠论5分钟或15分钟背驰，同时K线节奏也够了，我就买。但实践发现，小转大的情况很多，缠论在5分钟或15分钟的走势上没有出现买点，但第二天就涨了。这样让我错过了不少抢反弹的机会。还是决定放弃缠论操盘，因为缠论操盘较耗心力，而且要求经常看盘。还是我的数K线方法简单实用，容易达到机械化操作的目标。
4. 交易计划和交易日志。本月下旬，每天针对手里的持股写交易计划和交易日志，感觉心很平静。盘中不会再乱动了。基本上是每天早晨做计划，然后按计划下单，晚上复盘。下个月继续坚持这个习惯。

下个月策略：

1. 选股：只选放量突破不久的个股。
2. 持股：对于趋势没破的个股，尽量拿着，通过交易计划和交易日志，增加自己的持股能力。
3. 目标：锻炼自己跟随趋势的能力。尽量不做短线。
