
* Compare streamer
** peer streamer
** myseelite
** p2pcenter
* Javascript
** System Object
1. process
2. console
** boolean
| null           | FALSE |
| undefined      | FALSE |
| Object         | TRUE  |
| function       | TRUE  |
| 0              | FALSE |
| 1              | TRUE  |
| 0、1之外的数字 | TRUE  |
| 字符串         | TRUE  |
| ""(空字符串)   | FALSE |

如果&&左侧表达式的值为真值，则返回右侧表达式的值；否则返回左侧表达式的值。

#+BEGIN_EXAMPLE
var i=""&&"真值";//->i=""  
i="真值"&&"其他真值";//->i="其他真值"  
i="真值"&&"";//->i=""  
#+END_EXAMPLE
 
如果||左侧表达式的值为真值，则返回左侧表达式的值；否则返回右侧表达式的值。
#+BEGIN_EXAMPLE
var i=""||"真值";//->i="真值"  
i="真值"||"其他真值";//->i="真值"  
i="真值"||"";//->i="真值"  
#+END_EXAMPLE
 
* Node.js
** introduction
Node.js 服务端(脱离浏览器环境)的javascript
Node.js使用了Google的V8虚拟机（Google的Chrome浏览器使用的JavaScript执行环境），
来解释和执行JavaScript代码。 
Node.js事实上既是一个运行时环境，同时又是一个库。 
使用Node.js时，我们不仅仅在实现一个应用，同时还实现了整个HTTP服务器。
** install
1. goto http://nodejs.org/download/, download a binary archive.
2. tar xzvf /path/to/the/nodejs/archive.
3. add the following code to your .profile.
   #+BEGIN_SRC sh
   node_js_path=~/pkgs/node-v0.10.26-linux-x64/bin
   if [ -d $node_js_path ]
   then
   PATH=$PATH:$node_js_path
   fi

   export PATH
   #+END_SRC
4. =\. .profile=, then you can use node and npm
5. If node complains `can not find module xxx', you need set environment variable NODE_PATH:
   #+BEGIN_SRC sh
   node_js_root=~/pkgs/node-v0.10.26-linux-x64
   NODE_PATH=${node_js_root}/lib/node_modules/npm/lib
   NODE_PATH=$NODE_PATH:${node_js_root}/lib/node_modules/npm/node_modules
   export NODE_PATH
   #+END_SRC
6. If you import module with absolute path or relative path, node will search the file with same name and with extension .js or json.
   If you import module without path, it will search node_modules under the same directory.
   If node can not find node_modules dir, it will goto the parent dir to look for mode_modules until the root `/' is reached.
   If node can still not find node_modules, it resort to NODE_PATH.

** Tutorial
1. http://www.nodebeginner.org/index-zh-cn.html Node入门
   https://github.com/manuelkiessling/NodeBeginnerBook
** Notes
1. Node有一些核心模块，被编译进Node的二进制中，如http, child_process, fs (manipulate file system)
2. npm install numeral; formatting and manipulating numbers.
3. npm install clivas; A *interesting* library to manipulate terminal as a canvas.

* tools
** git
*** Usage
1. create repository jolly-notes on [[https://github.com/][git-hub]]
2. =git clone https://github.com/jollywing/jolly-notes.git=
3. change your cotents && commit to local (=git add= and =git commit=)
4. =git remote add origin https://github.com/jollywing/jolly-notes.git=
5. =git remote set-url origin https://jollywing@github.com/jollywing/jolly-notes.git=
   Important! if you skip this step, you'll get error when you push.
   The error is like: "error: The requested URL returned error: 403 while accessing ..."
6. =git push -u origin master=
7. In another location, you can  =git pull origin master=
8. try *rebase*.
*** msysgit (Git on Windows)
When you clone a remote repository, you'll meet a error:

#+BEGIN_EXAMPLE
$ git clone https://github.com/jollywing/jolly-notes.git
Initialized empty Git repository in e:/jollywing/jolly-notes/.git/
error: error setting certificate verify locations:
  CAfile: /bin/curl-ca-bundle.crt
  CApath: none
 while accessing https://github.com/jollywing/jolly-notes.git/info/refs

fatal: HTTP request failed
#+END_EXAMPLE

Solution:
: git config --global http.sslcainfo "/e/jollywing/installed/Git/bin/curl-ca-bundle.crt"

*** errors
1. non-fast-forward error, somebody else has commited something to the remote repository,
   before you push, you nell pull at first.
*** github
1. delete a repository. Open the repository page, click /settings/ in the
   right pane, click the button "delete this repository" in the bottom.
** android
1. the best file manager: es file manager
2. android terminal emulator.
   The commands supported:
   https://github.com/jackpal/Android-Terminal-Emulator/wiki/Android-Shell-Command-Reference
* Notes
** address
北京市石景山区石景山路31号盛景国际大厦C座12层  邮编：100043
** company email
user: w*j*****
passwd: j****w***
question: my good boy?
answer: 1****6
** wirless network
1. apecn-work; passwd: apecn-654
2. live; passwd: zh***h**f***
** sopcast account
- =jiqing_wu@***.com; t******j=
** linux
account:r; 5*****j***y
* Emacs
** custom emacs home
** make theme
~/.emacs.d/spring-theme.el

#+BEGIN_SRC elisp
(deftheme spring
  "A black on light green theme, to protect your eyes.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'spring
   `(default ((,class (:background "#99bb99" :foreground "black"))))
   ... ...
  ))

(provide-theme 'spring)
#+END_SRC
** gnus
M-x gnus-other-frame
* IT News
1. 2013.4, 百度继收购爱奇艺之后，收购了PPS。
2. 优酷收购土豆网后成为第一阵营，百度携手爱奇艺、PPS争夺第二阵营，搜狐视频、腾讯视频等都在步步紧逼，抢占视频行业市场。
3. peerflix 为用户交换DVD提供一个平台，peerflix 对每笔交换收取一定的费用。
4. BAT三巨头: BaiDu, ALi, Tecent.
5. 阿里巴巴收购高德导航，集成快的打车。
6. 腾讯开发的英雄联盟是目前全球在线人数最高的游戏，超过了魔兽世界。
7. 地图是百度的竞争力所在。
* BTlive
* btsync
ref: http://www.bittorrent.com/sync
AL32ADHNEBXGOLZVH7QBBNDY5UWREKAWZ

set up linux version

* Someday
** worktile: 协同工作
** 机顶盒的结构和原理
** Firewall traversing

** 科研项目
1. 国家科技项目申报

