
#+TITLE:2014年读书笔记

* 《问道——道家内证与生命科学》内容回顾
编者：张剑峰

** 油麻菜终南山寻仙记
作者：油麻菜

作者油麻菜通过萧道长的引荐见到了终南山上全真派张老道。
张道长每天练习道家密传的“金刚长寿功”，年逾百岁，身子骨还很硬朗。

张道长是老道医，文革时曾医好一个在医院治不好的人，结果文革时被他救活的那个人站出来批斗他。
真是个妖魔横行的年代啊！从那之后，老道长倒了药，烧了医书，不再给人看病。
对于现在中医的复兴，老道长很欣慰。

** 南山亭茶谭
作者南山如济结合参道修佛谈他对茶、琴、棋的体悟。

** 踵武前贤 爝火相传——对话中国式教育
张剑峰和几位倡导中国传统教育的人的对话，探讨如何在现代社会重树儒家教育。

** 道家内证医学漫谈
作者：徐文兵。这是紧扣书题的一章。

上古的巫文化是道教的先驱。

古代神医有超乎常人的本领（比如古典记载的身体透视功能）。

新中国之前的《医部全录》里有祝由科，包括画符，念咒。
新中国之后就删除了。

气和经络是中医的精髓。用西方的解剖方法是看不到经络的。
但中国有一些打坐有很深功夫的人反观内视能看到自己的内脏和经络。
李时珍在世时曾每晚打坐练功，在《奇经八脉考》中说：“医不知此，罔探病机。”

** 道医文化问答
张剑峰采访著名道医徐文兵和道家传人苏华仁。这也是扣书题的一章。

这章通过张剑峰的提问，介绍了道家的“精”“气”“神”“魂”“魄”的概念，
以及道医和中医的渊源和区别。

** 恬淡虚无 真气从之
张剑峰对南山散人的访问。
南山散人推崇静心和看淡生死。他说生老病死只是现象而已，并向张剑峰谈了他如何淡然地送走他父亲的情形。

南山散人也常读佛经的，谈话间常引用《心经》的句子。

** 道家炼养漫谈
张剑峰访问田堃建。也是扣书题的一章。

田从小身体虚弱，机缘巧合，他有幸结识了中国道协曹信阳老道长。
后来他阅读曹信阳注释的《道德经》，经常向曹请教，成了曹的弟子。
曹就给他传授经法，比如《太上老君说常清静经》、《元始天尊说得道了身经》。
曹也是让他少欲静心，养混元之气，后来田发现自己的小周天不知不觉间通了。

田喜欢一百二十八式的三丰祖师太极拳，每天练两三个小时。
他虽以道为主，但也读心经和金刚经的。
以前道教祖师吕洞宾也深入研究金刚经，还留下了注解。
大概因为《心经》和《金刚经》是谈世间实相的文字般若，大道相通，所以普遍地被修道之人奉为经典。

** 华叶递荣 经世致用——与梁冬关于中医文化的对话
梁东是北京正安医馆创始人，中医的弘扬者。
张剑峰想引导他谈些内证的经验，他却似乎对这块没什么兴趣。

** 为传统文化培土
——对话盛日先生：企业文化与传统文化的回归

盛日先生在自己的企业中推行传统文化，从日常生活中行住坐卧培养，让员工知“礼”。
他主张把儒释道的传统文化融入日常生活中。

** 天地有醍醐在其中
——禅修心要：惜缘与布施

这一张吴言生老师的演讲节录，完全是学佛的主题了。
惜缘，与人为善。布施，积善成德。
通过惜缘、布施，我们可以积极改造命运。

** 提及的书

- 空谷幽兰，一个美国人来到中国寻访高人隐士的见闻。
- 逝去的武林，一个武林高手讲述民国期间真实的武林。
- 万法归宗，讲掐诀念咒的书。

2014-01-13 Mon

* 两个伟大的女性
** 竹内多鹤
《小姨多鹤》刻画了两个感人至深的伟大女性：竹内多鹤和朱小环。
毋庸置疑，竹内多鹤是女一号。
张俭虽然是男一号，但女二号朱小环的光彩完全盖过了他。

多鹤是东北被日军占领时来东北垦荒的日本人的后代。
日本战败那年，她落到当地保安团手里，被卖给张俭做生孩子的工具。
几十年下来，她和张俭、张俭的妻子朱小环过成了一家人。
他们之间的感情感人至深。

多鹤是勤劳能干的。
从进了张俭家的门，每天都把家里收拾的干净整洁。
她保持着在日本家里的习惯，每天跪着把水泥地面也擦的光溜溜，一尘不染。
家里人的衣服都被她洗得干干净净，熨烫得有型有款。
要做到整洁，在日本是不难的。
在一个新中国的农村家庭，要维持整洁，需要多勤劳才能做到啊，但多鹤做到了。

当家里经济紧张的时候，多鹤出门打工砸石头。
她闷头做事，而且做事有方法，一个人能干好几个人的活。
后来又去工厂刻钢字，同样保质又保量。
一天的字刻下来，她的眼睛快瞎了，可她从不抱怨。
她没有时间抱怨，不是收拾家务就是打工挣钱。
把自己全部的时间奉献给了这个家。

多鹤是漂亮的，但她的漂亮不以身材取胜。
按严歌苓的描写，身材并不婀娜，走起路来甚至有些笨笨的。
她应该是秀发如云，明眸皓齿，一个很明媚的女子。
更吸引人的是，她举手投足间有中国人学不来的异域风情。
她鞠躬的习惯，说中国话时的奇怪声调更增添了她的魅力。

多鹤有过快乐的时光，就是和张俭瞒着小环幽会的时光。
可那时光非常短暂，不到两年。
他们的幽会被工厂抓了现行之后，张俭又和她疏远。
她的精神支柱是她的三个孩子。
可文革开始后，三个孩子又因为她的日本人身份疏远着她。
大孩张贴甚至一脚踢在她胸口上。
严歌苓多次写道：从那之后，多鹤就经常含着胸，好像一下上了许多岁数。
小环看在眼里，心疼不已。
我读到这里时，觉得多鹤实在太堪怜了，心里充满酸楚。

民族的野性。

那段时间她多么艰难啊。
张俭被判了死缓坐牢，她也被判为日本间谍。
带着绣有日本间谍的白袖标，被罚冲洗厕所。
去菜市场捡垃圾。
她曾多么想去死。
吃的还是给二孩留着。

当文革风潮过后，中日关系缓和，多鹤成为国际友人。
把生身母亲恨到死的张铁又一口一个妈地叫得亲热。
就这么一个不是东西的儿子。多鹤一句也没责备他就原谅了他。
大孩张铁最没有良心。
忘恩负义。又把小环扔到一边。
伸手跟家里要钱。汉奸嘴脸。也带着新中国无产阶级的性格特点。

张春美从小就乖巧，她虽然从不跟家里抱怨，但她被大环境影响着，不得不跟家里决裂。

二孩从小就有日本人气质的。
家里困难的时候，为家里省钱。
最有良心。
姐姐和哥哥都去了日本，他不去，他要留在中国陪着小环。


虽然多鹤是个和我们有着深仇大恨的异邦的女子。
但那个民族也有很多可贵的品质，比如
整洁，有礼，沉静，有条理，认真。


** 朱小环

朱小环是张俭的原配。虽然不象多鹤那么明媚。但身材一直很好。
按严歌苓的描述是：流水肩和黄鼠狼的腰。
眼睛虽然不大，但是灵巧俊俏。
因为自己曾因为日本人的追赶从牛上摔下来，不能再生养孩子。

朱小环也是能干的。
在50年代到70年代中国的政治风潮波及张俭的家庭之前，朱小环是大大咧咧、嘻嘻哈哈、好吃懒做的。
多鹤出门干活的时候，她也不干活，好吃懒做，主要是带带孩子串串门子。
轰轰烈烈的文革开始了，小彭当了厂领导，把张俭关进了监狱，判了死缓。
家里的生活靠两个女人维持。多鹤的日本人身份彻底暴露，也丢了工作，只能捡垃圾贴补家用。
这时主要靠小环了。小环靠骗和偷来维持家里的食物来源。
后来，她在楼下开了裁缝铺，靠自己的手艺和社交魅力，街上年轻的流氓阿飞都照顾她的生意。
就这样她和多鹤撑了下来。
在这个时候，她的坚强、乐观和能干表露无遗。
原来好吃懒做的朱小环认起真来，也能撑起整个家。

朱小环和多鹤的关系是微妙的。
她和丈夫张俭是亲密无间的，忽然他们之间插进来一个要陪张俭睡觉的女人。
她害怕这个女人会破坏她和张俭之间的亲密，但她深明大义，为了要孩子，她经常劝张俭去多鹤屋里睡。
她曾跟张俭说：等生了儿子，你就把她再装到麻袋里往山上一扔。
可她很快就不说这样的话了，她是个善良热心的人，她对多鹤有了姐妹感情。
当张俭真地把多鹤弄丢之后，她跟张俭急了，骂张俭黑了良心，逼着张俭到处去找。
当多鹤千辛万苦地自己摸回家，一开门，小环就把多鹤紧紧抱在怀里。
多鹤恨张俭，不和张俭说话。小环就故意带孩子出去玩，并叮嘱张俭要多鹤。
你看这个泼辣甚至有些粗鄙的女人多么可爱。

多鹤流产后，小环一直在医院照顾她。
听多鹤讲她们族人惨烈的逃亡，她一直忍着，回到家见到张俭就哭了。
这种同情已经超越了民族仇恨。从那之后，小环对多鹤更好。

当张俭和多鹤在工厂礼堂幽会，被抓了现行之后，
小环跑到工厂保卫部门，放下所有脸面说自己就是那个和张俭幽会的人，把张俭解救出来。
她深明大义的一面解救出来。

张俭坐牢后，她更是成了家里的主心骨。
她坚强乐观地活着。给张俭写信或是探监，她都编许多谎话给张俭希望，委屈却自己吞到肚子里。
要不是她，多鹤也早自杀了。

她心里有多少苦呢，只是不说而已。
张俭死了，多鹤、女儿春美、大孩张铁去了日本。二孩张钢在西南工作。
小环一个人带着黑狗，继续在马鞍山坚强的活着。

小环的性格比多鹤还要复杂，还有更多层面。
一个是中国女性，一个是日本女性，性格如此不同，却同样柔韧伟大。

** 姐妹情

两个人本来多不同的两个女人，还有民族仇恨和对抢一个男人的矛盾横在他们之间。
但吵吵闹闹几十年下来，她们变成了比亲人还亲的姐妹。
感觉小环和多鹤比她和张俭还要亲。

多鹤沉静、有礼、爱整洁、有条理。
小环热情泼辣、大大咧咧、坚强乐观。
两个人一起生活了几十年，潜移默化地被对方改变了。
小环从多鹤那里学到了认真和整洁。
多鹤也从小环那里学会了适当的“凑合”。

当多鹤从日本回来，和小环又一次紧紧拥抱。
你了解她们的过去，就会知道真是感人啊。




** 电视剧上的改动
电视剧上还是改了不少。
张春美似乎真疯了。
小彭更恶心。小人得势的妖魔。
阎学晶演的似乎瘫痪了。
阎学晶那身材实在不象小环。
孙俪演的也不象。
只有姜武演的张俭神似。
读完了一遍《小姨多鹤》，不忍再读第二遍了。

的一生太让人揪心了。


* 《乾道坤道》
1. 石高静重振全真南宗祖庭的故事。
2. 修行的初衷：克服遗传的心脏病。
3. 卢高极：道串子。正一道，霸占简寥观。
4. 卢高极：用双修来诱骗阿暖。
5. 卢高极：聘请印州艺专的女生，七仙女。
6. 卢高极：把阿暖送给周市长做干女儿。
7. 卢高极：把自己的女儿送给周市长做干女儿。
8. 卢高极：跟邴道长闹翻。
9. 印州琼山顶：南宗祖庭。
10. 应高虚：表演失败。迈阿密州坐化。
11. 祁高笃：还俗。
12. 祁高笃：大酒店。
13. 祁高笃：糜烂生活。吸毒，玩女人。
14. 祁高笃：玩滑翔伞。
15. 把逸仙宫卖掉，全捐献给逸仙宫的重建。
16. 第二十六代弟子：高字辈。
17. 露西。路嗣真。
18. 崇玄道院。
19. 道、经、师三宝。
20. 石高静随机度人，也影响了身边的人。
21. 把恬淡自然、天人合一推广到和地球环境和谐相处。
22. 得到道教前辈的帮助和指点。江道长，左院长。
* 《男人约会向北，女人约会向南》
约会方法与方式缺少了某些环节。
通过一次次约会，你会发现自己真正被什么样的人吸引。

每次约会后，你都要能够对约会对象做出评价。
Chi, 不漂亮, 个子小。家庭合适。
Zheng, 不安静，气质不符合。个子够高。
BKU, 不漂亮，个子小，河南人。学历气质可以。
HuangMin, 不漂亮，胖。性格够好。

个子够高，瘦一些，脸漂亮，年轻，气质安静。

1. 个子高，漂亮，让人羡慕，温柔体贴，不伦之恋。
2. 食之无味，弃之可惜。

如果是男人提出分手，女人会愤恨、不满、委屈。
男人也不会如释重负，轻松自在。
恰恰相反，女人倾诉和泪水会让他们充满负罪感。
如果你怀着愤恨或愧疚的情绪分手了，那么下次再恋爱，你可能会喜欢上与旧情人相似的人。
这是因为在你的潜意识中，你想通过这次恋爱解决上段感情遗留下来的问题。
嗯，爱情模式轮回的症结可能在这里。

好的结束意味着好的开始

唯有心门敞开，你才能了解自己的真实想法。

在一起的时候，为了达到结婚的目的，两个人试图改变自己的本性以迎合对方，
结果这种压抑本性的做法反而导致更深的误解和矛盾，于是争吵不断，剑拔弩张。
分手之后，两人放弃了去维持关系的努力，反而轻松许多，能够从容相处，变成了好朋友。
我们就是这样的吧。

当真爱出现在你面前，你“就会知道(just know)”。
然后你们就会用一生的时光去探索、去发现为什么TA就是你的另一半。

约会情侣间会产生四种基本的化学物质：身体上的化学反应引起欲望；
情感上的化学反应产生爱慕；心理上的化学反应引发兴趣；精神上的化学反应创造爱情。

约会初期：相互吸引、彼此感兴趣。

你可能爱上什么人，却不想与他结婚。

从心理上不要老想着寻找自己的另一半，而应该集中精力为爱热身，以便当他出现在你面前时，你就能立刻发现你的真爱。
一旦你自己已经准备好了，真爱就会出现。

为爱热身的重要环节是，逐渐了解你自己。
（我是谁，我喜欢什么，我讨厌什么，我能做些什么，我需要什么，我不需要什么）
一旦你已经明白自己对异性相当有吸引力，你就能够超越约会的第一阶段。
独立感是情侣间建立亲密关系的基石。

当你恢复独身的时候，切莫急于找到某个人和你共同生活。你首先必须找回自己。

一次只向一个女人敞开心扉。

爱情五个阶段。

第一阶段：吸引
第二阶段：不确定阶段
第三阶段：排他性阶段
第四阶段：亲密阶段
第五阶段：订婚

花时间去真正的了解某个人是促使你获得恋爱成功的秘诀。

男人如喷枪，女人似火炉。
女人是慢慢热起来的。思想上，情感上，然后才是身体上。

当男人流连于花丛中左挑右选，眼前花影憧憧，却似乎无中意人选，就表明他并不懂得建立标准的重要性。

男人越多地追求自己不爱的女人，越发不能感受到他可能会真心相爱的女人的身体吸引。
身体吸引。情感吸引。精神吸引。灵魂吸引。

女人
精神（趣味）吸引。情感（性格）吸引。身体吸引，灵魂吸引。

绝对不能只为尽快结婚随便找个人来委屈自己。

女人只要接受你为她做的任何一件事，都表明她在与你调情。

女人的调情信号：

当男人甘冒风险去感动她，女人就喜欢她了。
女人格外喜欢谈论计划、感情和她们目前的处境。

男人倾向于集中精力做一件事，女人可以同时处理很多事情。

几乎所有的男人走近亲爱的女人时，都会有失常态。其实大家都一样。

女人很了解男人失态意味着什么，因此她们并不会挑剔男人笨拙的反应。
你笨拙地与她搭讪攀谈时，她表面上若无其事，心里早乐开了花。

掌握赞美异性的艺术。
在正确的时间，把自己置身于正确的地点，然后奇迹才会发生。

产生情感反应的要素：
1. 不同的兴趣爱好。

没错，幸福的伴侣总是有着不同的兴趣爱好。
当然，他们会有许多共同的爱好，但有更多不同的爱好。

兴趣和爱好不同的人们会产生感情。
我们能够遇到与我们兴趣爱好不同的人的唯一途径就是偶然邂逅。
积极主动地到那些与我们兴趣爱好不同的人出没的地方去寻找。
如果我们只想与自己待在一起，就根本不需要找个伴儿。

尝试做新的事物。

改换作息时间。

2. 互补的需求。
3. 成熟。
灵魂伴侣的成熟程度通常是相同的。
光顾一些确定年龄相仿的人会去的地方。
4. 共鸣
有共同的价值观
* 麦肯锡教我的思考武器：从逻辑思考到真正解决问题
: （日）安宅和人 著，郭菀琪 译

*0. 事半功倍：高效高质地完成工作*

工作是为了产生成果，以时间衡量工作的是工薪族，以产出（造成的影响）衡量工作的是 *企业人* 。

提高生产力 = 删减劳力和时间但交出相同的成果 = 相同的劳力和时间交出更多的成果。

提高工作产出的秘诀在于 *把议题作为出发点* 。
所谓议题就是我们要查明的问题，即要对什么找出答案。

如何找到好的议题？
衡量一个议题有 *议题度* 和 *解答质* 两个指标。
所谓议题度是：找出该问题答案的必要性有多高，解决该问题的意义有多大。
所谓解答质是可以提供明确答案的程度。

如果一个议题的议题度很低，解答质再高，也不是一个好的议题。
你花再多时间去解决议题度低的问题，解决的质量再高，也难以做出有重大意义的成果。
如果你选择了一个议题度高的问题，即使解答得差强人意，别人也会觉得你做了很多工作。
（做学术研究，选择课题就是这样）
在商场上，如果想赚钱，就要寻找议题度高的问题。

因此，本节的建议是：
（1）中断没有意义的工作。
（2）抛开难易程度，找到有价值的问题。
（3）先提升议题度，再提升解答质。

本书下面就分四部分阐述了从议题出发的工作方法：
（1）议题思考（找到有意义的议题）；
（2）议题分析（将议题分解，用假说标明子议题，为解决该问题组织故事线）；
（3）成果思考（验证子议题乃至整个议题）；
（4）信息思考（汇总成果，生成论文或是简报）。

*1. 议题思考*

1.1 面对一个议题，要问自己类似以下的问题，判断它值不值得解决。

（1）为什么有必要找出答案？
（2）对接收者而言是否有震撼力？
（3）能否以具有说服力的方法验证？
（4）为此必须先弄清什么？

记得咨询智囊团的意见。杰出的人都拥有自己的智囊团。

1.2 使议题明确化。

为议题建立假说（命题）！
用语言和文字表达议题，加入主语和动词。
不要说：Linux优于Windows操作系统吗？
而要说：Linux优于Windows操作系统。

因为你下了个断言，你就会想办法证明你的断言。你就有了个努力的方向。
即使通过后面的验证，你发现自己的假说无法证明，
你也可以得出一个结论：Linux并不比windows操作系统好。

如果你的议题是个二选一的选择题，比如：某某是A还是B？
你可以这样建立假说：某某不是A，而是B。

（人的天性是一旦下了断言，就会想办法为自己辩护。
比如说，你心里想：我不幸福。接下来你就会情不自禁地思索自己哪些方面不幸福。
而如果你想：我很幸福，你又会情不自禁地思索自己有哪些值得珍惜的幸福。
你看，经常使用肯定式的断言，对增加我们的信心和幸福感很有帮助。）

1.3 好议题三要素：

（1）有本质性的选项。

不同选择会对未来研究产生重大影响。
比如 “项目应该用c++开发，不应该用python开发。”
这个议题的讨论结果将决定项目的技术路线和项目组的人员组成。

另外，要先查明最大的分歧点。
比如，如果议题“项目的开发能让公司盈利”不能得到验证。
则“项目应该用c++开发，不应该用python开发。”的议题也没有意义了。

（2）含有深入的假说

如果能验证推翻常识的假说，对全人类都是有意义的。
想想哥白尼说出“地球在围绕太阳转”时，人们感到多么震撼！
如果我们想提出某个领域内让人震撼的假说，可以列举该领域内人们普遍相信的常识，
从中检查是否有可以推翻的。如果找到竞争者未察觉的视角，我们就抢占了先机。

另外，以以新结构理解所见所闻，也能给我们新的视角，建立新颖的假说。
方法有：a.找共通点； b. 找相关性（A和B有某关系，B和C有某关系，推出A和C的关系）；
c. 找到群组（根据坐标轴分组）； d. 找到规则（或公式）。

（3）可以找到答案。

如果议题再有意义，却无法找出答案，也不是一个好议题。
世界上有意义但无法解答的问题太多太多了。
如果以你能力的极限刚好能解答一个有意义的议题，那么这个议题对你来说就是个好议题。
如果问题太复杂，只能找到部分答案，则将部分问题作为议题比较好。

1.4 搜集资料

为了建立一个好议题，你需要搜集资料，有以下注意事项：

（1）注意效率：粗略地获取用于思考的材料，只搜集主干结构的信息。
（2）接触一手信息。到一线去：车间、销售、实验室；cold call: 向不认识的人进行电话访谈。
（3）掌握基本信息：数字；问题意识（和议题有关的领域内常识）；整体架构（阅读综述、相关书籍、报告，暂时只看基础概念和原则）。
（4）不要搜集过头或知道过头，将调查深度保留在概要阶段。 /知道过头，会使自己独具的观点趋近于0/ 。

1.5 确立议题的五个方法

（1）分类细化，通过删减变量让议题明确。如把“商品”替换为“玫瑰花”。
（2）可视化。
（3）从最终情形倒退（如五年的人生计划倒推，来确定当前应采取什么措施掌控人生）。
（4）重复问“so what”，做出有意义的推断。
（5）通过思考极端的实例来建立假说。

*2. 议题分析（假说思考）*

2.1 分解议题

（1）分解成子议题，至每个子议题能找出答案的程度为止。
（2）如果发现找出答案有困难，可以尝试不同的分解标准。不同的分解标准导致不同的分析结果。
（3）有些议题可以按照WHERE，WHAT，HOW的模板来分解。
（4）没有模板可用，就倒推。
（5）分解依据MECE原则（彼此独立，没有遗漏）

2.2 组建故事线

        尽可能提早制作故事线
        以“假设提出的假说都是正确的”制作故事线
        故事线主轴
            共有问题意识及前提所需要的知识
            关键议题、次要议题的明确化
            针对各个次要议题的讨论结果
            综合性的含义
        模板（金字塔结构）
            并列“为什么”（归纳）
                案件A
                    为什么案件A有吸引力
                    为什么该着手处理案件A
                    为什么可以着手处理案件A
            空、雨、伞（演绎）
                空：x是问题（确认课题）
                雨：要解决这个问题，必须查明这里（深掘课题）
                伞：如果是这样，就这么办吧（结论）
    图解故事线
        为子议题绘制数据图表
        要大胆干脆地绘制
        步骤
            找出轴
                所谓分析就是进行比较
                定量分析的三个模板
                    比较
                    构成
                    变化
            意象具体化
                分析的可视化：展示比较所得的结果
                    有差异
                    有变化
                    有类型
            清晰指出获得数据的方法

* 把时间当作朋友
所有学习上的成功 所有学习上的成功， ，， ，都只靠两件事 都只靠两件事： ：： ：策略和坚持 策略和坚持， ，， ，而坚持本身就应该是 而坚持本身就应该是
最重要的策略之一。与其不停地找更好的方法 与其不停地找更好的方法， ，， ，还不 还不
如马上开始行动， ，， ，省得虚度更多的时间 省得虚度更多的时间。 。。 。 

这世界上有些事情或者道理，大抵上
可以分为以下四种情况： 
1.  实际上是正确的，我们也以为是正确的 
2.  实际上是错误的，我们却以为是正确的
3.  实际上是正确的，我们却以为是错误的
4.  实际上是错误的，我们也以为是错误的

不再让自己成为自己的大脑的奴隶 不再让自己成为自己的大脑的奴隶， ，， ，而是选择 而是选择
翻身做主人。

把尴尬记录下来；不被大脑的直接反应左右。

延迟满足

学知识要有快乐的心态，不然容易遗忘。
一个人有无自制能力和此人是否有才华，其实是完全不相干的。
不是每个欲望都能被满足，但是我们都有无穷无尽的欲望是个确
定的事实。
大多数人看法
惊人地类似甚至相同：如果有收获的话，那最好要马上有收获；如果没有收获的
话，那最好要马上有结。果

控制急功近利的天性。
罗列在哪方面这种天性尤为强烈？
挑出一个最重要的，
提醒自己控制这种天性。
工作和学习一定不要急功近利。

真正拥有耐心，甚至惊人的耐心的你，生活就会从此开始发生天翻地覆的变化。
通过有意减少性交次数，和延长性交之前的交谈爱抚时
间大大提高性生活的质量。

所谓的邪恶，就是最赤裸裸的、厚颜无耻的懒惰。
心智开启从意识到可以自律开始，而心智发展的过程就是克服懒惰的过程。

也许每个人的不幸都是一样的，
他一生中最多的经验是“半途而废”——各种各样的、各个方面的“半途而
废”。

任务太多， ，， ，无法全部完成 无法全部完成。于是你只好进行选择。事实上 事实上， ，， ，生活就是选择 生活就是选择

每天早上制作时间
预算，每天晚上记录时间开销。
每个星期找
一天花上一个小时，审计你这一周预算和实际开销。

同时做两件事。

所谓的脑力活动往往可以粗略地分
为这样几个部分：输入信息（阅读、观察），处理信息（思考），输出信息（记
录、写作、创作、分享、教授）。

** 战胜拖拉

　我不得不做。 我选择做。 
　　我必须完成。 我什么时候开始？ 
　　这个项目大且重要。 我能走出一小步。 
　　我必须做到十全十美。 我完全是一个凡人。 
　　我没时间玩。 我必须花时间玩。 

如果为失败而焦虑：

1． 可能发生的最坏情况是什么？ 
　　2． 最坏的情况真的发生之后我该怎么办？ 
　　3． 如果最坏的情况真的发生，我将如何减轻痛苦，并拥有尽可能多的快乐？ 
　　4． 我将拥有哪些替代性的选项？ 
　　5． 为了降低这种可怕事件发生的可能性，眼前我能做些什么？ 
　　6． 有没有任何我现在就可以做的事情，来增加实现目标的机会？ 

最容易拖拉的人，即是那些最害怕困难、批评、失败以及担心专注于一个项目而失去其他机会的人。 

只有在我们担心自己的价值感与独立感受到威胁的时候，只有在自然驱动力和富有成效的活动受到威胁或压迫的时候，我们才会表现懒惰。 

 你不能停下来，你总是要不断地尝试。生活与工作都是艰难的；它对你来说不会是那么轻而易举的；只有做了大量的工作之后，你才能栖身于胜利之中。最好习惯于冷酷的现实，因为成人时代比孩提时代更糟糕；当你在外面玩耍时，某个灾难正在角落里潜伏着，等待时机向你发动突然袭击。 

P55 拖拉者区别于高效者的物种自我陈述： 
　　 
　　（1）“我不得不做”的消极想法（用“我选择做”代替） 
　　（2）“我必须完成”的消极想法（用“我什么时候开始”代替） 
　　（3）“这个项目大且重要”的消极想法（用“我可以走出一小步”代替） 
　　（4）“我必须做到十全十美”的消极想法（用“我完全是个普通人”代替） 
　　（5）“我没时间玩”的消极想法（用“我必须花时间玩”代替） 

P103 逆向心理学 
　　（1） 在单个项目上，每周花费的时间补超过20小时 
　　（2） 在单个项目上，每天花费的时间不超过5小时 
　　（3） 必须锻炼或玩耍，每天至少1小时 
　　（4） 你必须每周拿出一天来什么都不干 
　　（5） 以开始从事30分钟高质量的工作为目标 
　　（6） 进行一次不完美，但首先完全符合人性的努力 
　　（7） 从小事做起 

　P105 如何安排逆向日程表： 
　　 
　　1. 只安排下列事情： 
　　（1） 先前已经决定好的时间，比如吃午饭、睡觉、开会 
　　（2） 自由时间、休闲、阅读 
　　（3） 交往，和朋友聚会 
　　（4） 健身运动 
　　（5） 常规事务，比如上课、医院、交通 
2. 只有当你完成了至少30分钟的工作之后，要把有关项目的工作列入逆向日程表中。 
　　3. 只对那些代表着至少30分钟不间断工作的时间段予以好评。 
　　4. 在每个时间段的工作结束之后，奖励自己休息一次。 
　　5. 跟踪每一天、每一周用于高质量工作的时间。 
　　6. 每个星期始终留出一天用于休闲或处理杂务。 

