#+TITLE: 编程笔记
#+OPTIONS: toc:2 H:3
* 编码风格
** google编码规范
Google是个伟大的公司，为我们提供了各种优质的服务。
它的成功离不开对开源项目的积极参与，它也从开源社区获益良多。
为了让开源爱好者更好地参与google项目，google放出了一些编码规范。

为此，google专门在 [[code.google.com]] 上建立了一个项目：[[http://code.google.com/p/google-styleguide/][Google Style
Guide]] ，给出了一系列 google style guides，包括 [[http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml][C/C++编码规范]] 、
[[http://google-styleguide.googlecode.com/svn/trunk/pyguide.html][Python编码规范]] 、[[http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml][JavaScript编码规范]] 、[[http://google-styleguide.googlecode.com/svn/trunk/objcguide.xml][Objective-C编码规范]] 以及
[[http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml][HTML/CSS 编码规范]] 。

同时，Google为Emacs用户提供了 [[http://google-styleguide.googlecode.com/svn/trunk/google-c-style.el][google-c-style.el]] ，
用于设置 cc-mode 的缩进风格，对 C, C++, java, ObjectiveC, awk等
多种语言有效。

下载 ~google-c-style.el~ 后，放入你的Emacs load-path，
在 ~.emacs~ 中添加如下代码：
#+BEGIN_SRC emacs-lisp
(require 'google-c-style)
(add-hook 'c-mode-common-hook 'google-set-c-style)
#+END_SRC

注意，google编码风格中，基本缩进是两个空格，
习惯缩进四空格的人一开始可能会不习惯。

2012-06-09

* Java
** 包内的类不能引用默认包中的类

用Eclipse写程序时，发现一个问题：当一个位于某个包中的类 (代码顶端
有 package xxx;) 访问 默认包中的类 (代码顶端没有 pacakge xxx;) 时，
代码检查通不过。

我怀疑是否Eclipse对此做了限制，于是就用 Emacs 试验了一下：

建立B.java，定义 class B：
#+BEGIN_SRC java
class B
{
  public void print()
  {
    System.out.println("This is an object of B class.");
  }
}
#+END_SRC

建立A.java，定义class A，A在test命名空间中，引用B:
#+BEGIN_SRC java
package test;

class A
{
  public static void main(String [] args)
  {
    B b = new B();
    b.print();
  }
}
#+END_SRC

=javac B.java A.java= 发现不管A.java中是否 =import B= ，编译都不通
过，看来是javac的限制。

通过网上搜索发现，用java 1.2, 1.3时，是可以从包中引用默认包中的类
的，但java 1.4之后就不行了：[[http://java.sun.com/javase/compatibility_j2se1.4.html][Java 1.4兼容文档]] 中有说明，并建议把所
有在未命名的名字空间（默认包）中的类放到某个命名空间中。

无奈，只好顺从吧。

2012-06-10
