
#+SEQ_TODO: TODO(t) ABORT(a) DONE(d) 

* OpenX (Revive Adserver)
AS3 需要广告平台的API?
as3 调用 javascript 需要浏览器的支持。

login the revive adserver
get the tag
put it to html.

CPC: cost per click, 按点击收费.
CPM: cost per mille, 每千人收费.
CPA: cost per action.

其中CPC和CPM比较流行，最为流行的是CPM.
* CasperCG
Question: The NVIDIA OpenGL driver lost connection with the display driver due to exceeding the windows Time-Out limit and is unable to continue.
What does it mean?
If you received this message from an application (on a pop up message or in the Event Log), the application was unable to continue rendering because the Microsoft Windows imposed time limit (TDR) was exceeded. This is normally the case when the workload sent to the Graphics Card is greater than what the graphics card can process in the normal timeout of two seconds.

Two possible solutions to try would be:

1.Reduce the graphics workload if possible, such as rendering to a lower resolution or with less detail.


2.Increase the timeout to allow more time to complete the really tough
rendering parts. Microsoft provides the information on how to modify the
Windows Registry to achieve this.

OpenGL message “lost connection” 显卡已停止响应
简单的说，出现这种错误的原因是由于显卡处理的数据量过多，导致消耗时间过长。

从Windows Vista开始到Windows 7，加入了对GPU的约束，当响应时间超过两秒时，就会强制停止GPU运行，并强行恢复。结果就是突然黑屏，然后通知栏弹出信息提示显卡驱动停止响应并已恢复。在windows xp中不会有这种情况发生。

大部分时候，用户并不希望这种情况发生。解决方法是停用windows的GPU超时检测。

在注册表：HKLM\System\CurrentControlSet\Control\GraphicsDrivers 下新建项目
TdrLevel：REG_DWORD 并设置为 0。禁用检测。重启即可生效。

 

TdrLevel: REG_DWORD. The initial level of recovery. The possible values are:

TdrLevelOff (0). – Detection disabled.

TdrLevelBugcheck (1) – Bug check on detected timeout, for example, no recovery.

TdrLevelRecoverVGA (2) – Recover to VGA (not implemented).

TdrLevelRecover(3) – Recover on timeout. This is the default value.

** ABORT HACK VB CLIENT 
*** check out playout client source code
: git clone https://github.com/SublanTV/CasparsPlayoutClient.git
*** try to build
1. Problem: 无法打开工程文件
   Reason: 工程文件比环境版本高。
   Solution: edit sln file. change =Microsoft Visual Studio Solution File, Format Version 12.00= to
    =Microsoft Visual Studio Solution File, Format Version 11.00=

2. Problem: 无法在证书存储区中找到清单签名证书。
   Reason:
   Solution: 工程->属性->签名->uncheck ClickOnce清单签名 
3. Problem: 依赖项目logger无法加载
   Reason: 该项目不可用，不在 source tree 里。
   Solution:
*** replace the icon
*** build
** HACK OFFICIAL CLIENT
*** OSC
osc is /open sound control/ protocol,
which sends real-time data and events from CasparCG Server over UDP.

User can configure or edit OSC output layer.
*** GPI
General Purpose Input.
GPI/GPO/GPIO, triggering through special hardwares.

MIXER include ATEM and tricaster
* CMP
On server PC-
Make a folder on server computer's D drive. Let us say mymedia
Right click this folder---property---sahring. Share this folder.
Right click on my computer--map network drive. Drive z--Folder= \\mypcname\mymedia
Make sub folders on this z drive named video, template, log, thumbnail.
Now modify you casparcg.config file as below
Code: Select all  <paths>
    <media-path>z:/video\</media-path>
    <log-path>z:/log\</log-path>
    <data-path>z:/data\</data-path>
    <template-path>z:/template\</template-path>
    <thumbnails-path>z:/thumbnail\</thumbnails-path>
  </paths>

Now on client PC
Right click on my computer--map network drive. Drive z--Folder= \\serverpcname\mymedia
Now run the server on server pc and Client on client pc.


** Template module

f0 is the name of textfield and loader1 is the name of dynamic image in
template. Name of textfields are automatically retrieved from template but
loader name are not. So loader1 name is given here for testing purpose. And
its default value has been given so that you don't have to fill anything
for testing. It will only work if a uiloader is there in template and its
instance name is loader1. And a method has been defined like this.

Code: Select allif (element. @ id == "loader1")
{
loader1.source = element.data.@value;
}

After installation of CMP from CasparMediaPlaybackSetup\Release\setup.exe, Three folders are created as c:/casparcg/_media, c:/casparcg/CMP, c:/casparcg/mydata
Note- For proper working of example templates in remote server, install this client on remote server PC also.


* ffmpeg
** ffmpeg player
ref: http://dranger.com/ffmpeg/tutorial01.html
Movie file is a container. such as AVI and Quicktime.
In this container, there are a bunch of streams, such as audio stream and video stream.
A data element in a stream is called *frame*.
Examples of codecs are DivX and MP3.
Packets are read from stream.
For our purposes, each packet contains a complete frame or multiple frames as for audio.
#+BEGIN_EXAMPLE
10 OPEN video_stream FROM video.avi
20 READ packet FROM video_stream INTO frame
30 IF frame NOT COMPLETE GOTO 20
40 DO SOMETHING WITH frame
50 GOTO 20
#+END_EXAMPLE

YUV = YCbCr
YUV is an analog format and YCbCr is a digital format.
is a way of storing raw image data like RGB.
Y is the brightness (or "luma") component, and U and V are the color components.
** compile a ffmpeg with old api
The avio.h from release 0.5 defined URLContext.

1. download or git clone FFmpeg-release-0.5;
2. ./configure --prefix=/home/jolly/job/ffmpeg-dev-0.5
3. make (!! if you are using unix, you need use *gmake*)
   : /usr/include/sys/soundcard.h:981:2: error: unknown type name 'u_char'
   I need include <sys/types.h> in the source file.
   and reconfig with ./configure --prefix=/home/jolly/job/ffmpeg-dev-0.5 --extra-cflags="-D__BSD_VISIBLE"
   then gmake again.

* Opentracker
** Make with _DEBUG enabled.
: make all
will create both opentracker and opentracker.debug.

Try to enable WANT_SYSLOGS

* goalbit-self-make
1. # error No UTF8 charset conversion implemented on this platform!
* Goalbit
** mail to goalbit sales
*** >>>
Hello, dear manager

My name is Jiqing Wu.
I am a techinque manager in a Chinese video broadcast company.
We want to use your goalbit plus service to reduce our bandwidth cost.

I tried your demo and want to learn more about goalbit.

1. If I want to broadcast our video, what goalbit module can support?

2. Can golbit plus encode the video stream to publish?

3. I know P2P network need a tracker, where the tracker of goalbit is placed?
   If we buy your product, will you provide us the tracker as a module?

4. I learn about that goalbit has its own super nodes to assist p2p, 
   can we deploy our own super nodes? and how to deploy?
   would you provide us the supernode module?

5. If we want to collect the information of our peer clients, 
   to what degree can goalbit plus support?

6. Now, we are in China Mainland.
   It takes more than 5 minutes to wait your demo to play.
   It's too long to tolerate. If we brocast the video from China,
   can it start to play in a tolerable interval?

If we buy your products, which form of products would you provide? software or hardware?
Quote a price, Please.

Waiting for your reply.

Your sincerely,
Jiqing Wu.
2014-04-18 Fri

*** <<<, relay to Haitao
Dear Jiqing Wu,

Thank you for your interest in our product and services.

I think that we can have a chat in order to better understand your needs.
为了更好地了解您的需求，我认为我们可以谈一下。
Please tell me a convenient date for you.
my skype is: goalbit
my gtalk is: goalbit@gmail.com

A fast answer about your last questions:

1. If I want to broadcast our video, what goalbit module can support? 
GoalBit Plus works as a delivery network, it accepts several streaming protocols as input (rtmp, rtp, mms, http and HLS).
If it is necessary, GoalBit Plus transcode the streaming in the server in order to obtain an HLS streaming (compatible with android, apple and flash).
（问：如果我们自己广播视频，goalbit如何支持？
答：GoalBit Plus是一个内容交付网络，它能接受几种流协议作为输入，比如RTMP, RTP, MMS, HTTP, HLS。
如果有必要，Goalbit Plus会把你的流在服务器端进行转码以得到HLS流，主要是为了兼容Android，苹果和flash播放器。）

2. Can golbit plus encode the video stream to publish? 
We accept 3rd party encoders, like wirecast, adobe live encoder (free), ffmpeg (free).
Typical configuration is to use Flash Media Encoder in order to generate a compatible streaming and push it into Goalbit Plus servers.
After the acquisition, our servers exchange the live content between them and serve the content in traditional streaming and p2p streaming.
（问：goalbit支持视频流的编码吗？
答：我们接受第三方的编码器，比如wirecast, adobe live encoder和ffmpeg。
为了生成兼容大多数设备的流，典型的配置是使用Flash Media 编码器，编码后推送到流媒体服务器。
获取流后，我们的服务器互相交换直播内容。然后以传统的方式或是P2P的方式提供服务。）

3. I know P2P network need a tracker, where the tracker of goalbit is placed? If we buy your product, will you provide us the tracker as a module? 
Yes. The tracker is part of the goalbit plus server software.
（问：我知道P2P网络有一个tracker，goalbit的tracker部署在哪里？如果我买了你的产品，你会提供给我们tracker吗？）
（答：是的，tracker是goalbit plus服务器软件的一部分。）

4. I learn about that goalbit has its own super nodes to assist p2p, can we deploy our own super nodes? and how to deploy? would you provide us the supernode module? 
There are a lot of academic work behind goalbit protocol, currently we are in version 3.0 and most documentation is about 1.0.
Yes, GoalBit Plus provide you with super nodes (currently streaming servers) in order to help in the delivery.
In summary, our solution includes all the necessary pieces in order to deliver live content to end users, you must provide a live streaming URL (for example an RTMP from Adobe live encoder) and our server does the rest, including:
    - transcoding if necessary
    - replicate the content between several servers
    - load balancing of end users between servers
    - deliver the content in traditional streaming (HLS) for non compatible devices, and deliver the content in p2p streaming (android and PC currently)
    - etc
（问：我了解到goalbit有自己的超级节点，我们可以部署自己的超级节点吗？如何部署，你可以提供给我们超级节点的软件模块吗？）
（答：针对goalbit协议有大量的学术研究，当前我们的版本是3.0，而大多数文档是关于1.0的。
是的，为了辅助内容交付，Goalbit Plus会提供给你超级节点（目前就是流媒体服务器）。
总而言之，我们的方案包含所有必须的组件，用以为终端用户提供直播服务，
你需要的是提供一个直播流的URL，比如来自Adobe直播编码器的一个RTMP流），我们的服务器会为你完成其余的工作：
- 必要的转码
- 在几个服务器之间复制视频内容
- 根据用户情况在服务器之间进行负载平衡
- 对于不兼容的设备，用传统的流（HLS）传输。对于android和PC，用P2P的方式交付内容。

5. If we want to collect the information of our peer clients, to what degree can goalbit plus support? 
We provide real time stats from our servers, as you can see in:
    http://www.goalbit-solutions.com/demo
    and with more details in: http://trial.goalbit-solutions.com/goalbit-media-server/tracker/stats/bigbangtheory
We also works with google analytics in order to collect and summarize the monthly stats.
(问：如果我们想收集客户端的信息，goalbit plus可以支持到什么程度？)
（答：我们提供实时的信息统计，你可以看看这里。
    http://www.goalbit-solutions.com/demo
更详细的，可以看这里： http://trial.goalbit-solutions.com/goalbit-media-server/tracker/stats/bigbangtheory
【可以看到连接的结点数，每个结点的ip，通过P2P下载或是上传的数据量，从服务器下载的数据量。】
为了收集和汇总每月的数据，我们也用google analytics处理数据。

6. Now, we are in China Mainland. It takes more than 5 minutes to wait your demo to play. It's too long to tolerate. If we brodcast the video from China, can it start to play in a tolerable interval? 
Yes. Please read our last performance test: http://www.goalbit-solutions.com/www/download/goalbitPlus-testingPlanResults.pdf
We worked a lot in order to have the same buffer than traditional streaming.
The problem with your 5 minutes is that our trial streaming server is far away from you. 
You can validate it, please go to http://trial.goalbit-solutions.com/goalbit-misc/gpa/play/ and try:
    GPA disable (i.e. traditional streaming in HLS)
    GPA requeried (i.e. p2p streaming)
    you will found similar starting time in both technologies, and it can be improved if you have a server close to the users
（问：现在我们在中国大陆，试验你们demo的时候，需要5分钟才能播放。等待时间长到不能容忍。如果我们从本地广播视频，是不是启动延迟会减小到可以容忍的程度？）
（答：是的，请读我们最近的性能测试： http://www.goalbit-solutions.com/www/download/goalbitPlus-testingPlanResults.pdf
为了减少缓冲时间，我们做了大量的工作。关于你的5分钟的问题是因为我们的试验服务器离你太远了。
为了验证这一点，你可以去 http://trial.goalbit-solutions.com/goalbit-misc/gpa/play/ 试一下：
GPA disable （传统方式）和 GPA required （P2P方式），你会发现两者的缓冲时间差不多。
如果服务器离用户近，缓冲时间会得到改善。）

7. If we buy your products, which form of products would you provide? software or hardware? 
We offer SaaS (including hosting from a 3rd party) or selfhosted (where you provide the hosting infrastructure)
Both have a monthly price based in the size of the deployment.
In order to give you a quotation you must provide us with information about your company (name, address, contact, etc.)

（问：如果我们买了你的产品，你们会以哪种方式提供产品，软件还是硬件？）
（答：我们提供 SaaS，我们的软件部署在第三方服务器上， 或者selfhosted，即你们自己提供硬件来部署。
都是基于部署规模按月计费的。
要谈价格的话，你必须提供给我你们公司的信息，包括名称，地址，联系方式）。

best regards,
    Pablo

*** prepare skype with goalbit
Dear Pablo,
Thank you for your detailed answer.
I have added your skype (goalbit), my skype ID is linuxer-wuchen.

My company is Beijing ASIA Pacific East Communication Network LTD (APECN), located at
12F, Building C, Royal international square, No.31 ShiJingShan Rd., Shijingshan District, Beijing, P.R. China.

You can check it at http://www.apecn.com/, but it only has Chinese version.

I want to talk the following questions with you:

1. We want to deploy goalbit on our hardware, which software modules will you provide?
2. If we want to make our own android client (apk), will you provide us goalbit SDK?
3. Where the tracker placed? Is it based on Opentracker, or KAD protol implemented in each peer?
4. If we deploy our goalbit network, does it need to communicate with your goalbit network?
   Or can we watch your programms provided by your goalbit network through our goalbit network?

When will you go online? Let us have a chat.
I'm online from 9:00 to 17:00 (China timezone) today and tomorrow.

Your sincerely,
Jiqing Wu

*** quote a price, please
Hello, Pablo!

I'm the technical manager of ASIA Pacific East Communication Network LTD.
I has written a mail to you.
I told you that my company want to buy your goalbit service to broadcast our programs.
At that time you gave me your skype and gtalk.

However, I can not find you on skype (goalbit?).
Because of the 'Great FireWall' of China, my gtalk often goes offline.
In addition, the clock difference between us adds the difficulty of chating with you.

So I write mail to you again. Don't mind my discourteousness, please.

My company is Beijing ASIA Pacific East Communication Network LTD (APECN),
located at 12F, Building C, Royal international square, No.31 ShiJingShan
Rd., Shijingshan District, Beijing, P.R. China.

You can check it at http://www.apecn.com/, but it has only Chinese version.

Would you give me a price list of your products, please?
I'll look forward to your reply.

Your sincerely, WU Jiqing
The Technical manager of APECN.

*** answer from Pablo
<<<<
On 06/25/2014 05:20 PM, sales@goalbit-solutions.com wrote:

Dear WU Jiqing,
Thank you for your contact.
About pricing, our products and services starts with a price of 300 usd/month (for a single server and a minimal support).
I need to understand better your need in order to give you a quotation. Could you define a date for a chat meeting?
For example next Tuesday 7/1 at 8am (Beijing timezone) (my local time Monday 6/30 at 9pm).
best regards,
    Pablo

<<<<
Dear Wu,
It is Monday 6/30 at 9.30pm. 
I do not see you online (skype nor gmail). I will close the chat now.
Please define a new date for the call.
Best regards,
    Pablo

*** date for a chat
Dear Pablo,

I'm sorry for my absence on skype.
I start work at nine. So I missed your message.

Now I want to invite you to have a chat,
I will go to my office earlier.
Would you be available on Wednesday 7/09 at 8am (your local time maybe 7/08 at 9pm)?
I'll wait for you on skype.

Best regards,
    Wu Jiqing
    2014-07-08 周二

*** Chat with Pablo

Goalbit was started in 2008, offering innovative video solutions over internet.
currently we are offering the goalbit plus product.
its main objetive is to deliver the content from servers to end users.

it is a simple management system and a set of streaming servers,
and sometimes a video player at the client side.

for streaming server there are three options:
1. our own streaming server, called goalbit media server
2. our add on for Wowza streaming server (a very popular streaming server)
3. any CDN that offer HLS (http live streaming protocol)

we offer the three options because each is convenient in differnet context

for end user software, there are different options

1. native player in android, flash player in browsers, etc
2. P2P plugin: an SDK for android devices, a desktop application for windows

again both options are necessary/ or convenient in different context

typical configurations are:

if you need to stream in other protocols than HLS, for example smooth streaming, then we use Wowza
if you have Wowza servers, then use our wowza addon instead our goalbit media server
if you want our best performance product, and HLS is enough, then we use goalbit media server

about client side the decision is easier?

we try to use the p2p plugin, and if it not possible then native player is used
therefore we cover android, iOS, windows and linux

how we offer our product?

usually:

a setup fee + monthly payment
setup cover installation
monthly payment covers licenses and support
our support is an agreement between both parties
we agree how many hours per month we will dedicate to upgrade, answer your questions, etc

yes, we does not offer appliance, we install the software in your hardware?
we does not offer hardware outside our country?
but we have resellers in many countries?


usually our customers prefer do not pay the cost of ownership?
and pay per month?
why do you want to pay in one payment??
(it is not a problem, we are an small company that addapt us to our customers)

I can give you a quotation for a one payment, but I need to known more about the sizing of the project?

How much users of goalbit plus are there now??

no so much, most of them are in our previous version of the software.

goalbit plus has a focus in android device, and we are working with hardware developers?
previous version was used for 300.000 of users?
and 20 providers?


goalbit plus is used by Pluggy and FPT (large telco)?
FPT from Vietnam?

everything run from your infrastructure?
tracker is part of our streaming server?
but 1st question to answer is: what is the best strreaming server for you?

please go to http://goalbit-solutions.com/www/platform?
there is a picture at the end?
it includes all the components?

at the server side, two software products: goalbit manager, and goalbit media server?

goalbit manager offer an API for development?

and a web interface in order to operate it?

you can add/remove channels?

change the load balancing between servers, etc?

usually 1 or 2 servers with goalbit manager are enough

then the goalbit media servers
they are designed in order to scale with number of users and number of channels
transcoding,
HLS delivery?
P2P delivery?
tracker?


because we expect thousands of users per server?
and it is largest than any practical swarm of peers?

http://trial.goalbit-solutions.com/goalbit-media-server/tracker/stats/bigbangtheory?
it is the stat of a demo channel as a goalbit media server is offering?


http://trial.goalbit-solutions.com/goalbit-media-server/tracker/graphs/bigbangtheory?
and with some graphics?


at the client side?
in order to offer the service you must have a web portal from where you offer the service?
and/or an android application?

our sample code includes an SDK of our delivery technology?
for browser clients the integration is simplest?

for example http://trial.goalbit-solutions.com/goalbit-misc/gpa/play?
there is a list of channels in our demo app?

as I told you, we are not offering perpetual licenses, but to give you a reference of price?

1 x Goalbit Manager     +     2 x Goalbit media server (up to 100 TB/month)   +    unlimited end users (with P2P or without)?

installation server + support for a year (up to 4 hours/month)?

for a one time price of 14.000 USD?


?9?:?22 the same, with a monthly: 750 USD/month?

** survey
1. Goalbit Media Player
With the Goalbit Media Player (desktop and browser plug-in editions) you
can play and record video streams from the web, and you can live broadcast
yourself with a home Internet connection.

2. Also, you will need the Starter
Suite in order to distribute GoalBit channels in the Web, and in order to
do a web broadcast from the GoalBit Media Player browser plug-in.

3. VLC = Video Lan Client.
VideoLAN是一个开发通过局域网（LAN）播放视频及其他媒体格式的软件的计划。最初
开发了两个媒体流媒体程序VideoLAN Client（VLC）及VideoLAN Server（VLS），然而
大部分的VLS功能都逐渐整合進VLC，所以就將VLC改名為VLC media player。
** make install on centOS
1. git clone git://git.code.sf.net/p/goalbit/code goalbit-code
2. No configure file; autoconf -v; 
   #+BEGIN_EXAMPLE
   configure.ac:446: error: m4_undefine: undefined macro: AC_DEPLIBS_CHECK_METHOD
   configure.ac:446: the top level
   autom4te: /usr/bin/m4 failed with exit status: 1
   #+END_EXAMPLE
3. ./bootstrap; 
   #+BEGIN_EXAMPLE
   configure.ac:5366: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
   autoreconf: /usr/bin/autoconf failed with exit status: 1
   #+END_EXAMPLE
4. yum install libgcrypt-devel; ./bootstrap; SUCCESS!
   Now we have configure.
5. libmtp-devel
6. libcddb, require libcdio.so.7, but there is only libcdio.so.10, so I downloaded the sourcecode.
   wget -c http://prdownloads.sourceforge.net/libcddb/libcddb-1.3.2.tar.bz2
   tar xjvf libcddb-1.3.2.tar.bz2
   cd libcddb-1.3.2; ./configure; make; make install; make clean; *sudo ldconfig*
7. configure: error: Could not find libmad on your system: you may get it from http://www.underbit.com/products/mad/. Alternatively you can use --disable-mad to disable the mad plugin.
   mad = mpeg audio decoding library. sudo yum install libmap-devel.
8. you must provide a gme-tree.
   /gme-tree/: It is a very rare game format, so, skip it
   GME is a library to parse various file formats, especially from old games.
9. Give up, change to FreeBSD.

** make install on freeBSD
1. sudo pkg install autoconf; ./bootstrap;
   #+BEGIN_EXAMPLE
   autoreconf-2.69: failed to run aclocal: No such file or directory
   #+END_EXAMPLE
2. =sudo pkg install automake=, run ./bootstrap again.
   #+BEGIN_EXAMPLE
   configure.ac:446: error: m4_undefine: undefined macro: AC_DEPLIBS_CHECK_METHOD
   configure.ac:446: the top level
   autom4te-2.69: /usr/local/bin/gm4 failed with exit status: 1
   aclocal-1.14: error: echo failed with exit status: 1
   autoreconf-2.69: aclocal failed with exit status: 1
   #+END_EXAMPLE
3. It's because libtool missing. =sudo pkg install libtool=, then run ./bootstrap again.
4. =./configure=.
5. =./compile=.
   #+BEGIN_EXAMPLE
   /usr/local/bin/ld: cannot find -ldl
   #+END_EXAMPLE
   The dlopen/dlsym functions are built into libc on FreeBSD, so there's no need for a libdl
   : sudo ln -s /usr/lib/libc.so /usr/lib/libdl.so
6. add ffmpeg-release-0.5
7. =error: implicit declaration of function= the function did not declared in header.
8. USING gmake INSTEAD OF make.
9. sed on linux and sed on unix are different.
   Hack the goalbit-0.7.7/modules/gui/goalbit/qtgb/Makefile
   #+BEGIN_EXAMPLE
   ifeq ($(findstring freebsd,$(host_os)),freebsd)
       sed 's/QT_BEGIN_MOC_NAMESPACE/ /g' $@ > $@
       sed 's/QT_END_MOC_NAMESPACE/ /g' $@ > $@
   else
       sed -i 's/QT_BEGIN_MOC_NAMESPACE/ /g' $@
       sed -i 's/QT_END_MOC_NAMESPACE/ /g' $@
   endif
   #+END_EXAMPLE

** code
1. What is SCRAPE. A client scrapes in order to determine whether or not to
   send an /announce/ requesting more peers. Sending a scrape result is
   usually less bandwidth consuming than sending a list of peers.

** try with opentracker
1. under "./modules/bittorrent/goalbit/btv_tracker/", is /open-tracker/.

** Parse makefile
1. cd src to make libvlc
2. cd bin to make vlc
.MAKE: $(am__recursive_targets) all check install install-am \
	install-strip
** source tree
#+BEGIN_EXAMPLE
.+--compat
 |    |
 |    +--asprintf.c (replace asprintf of GNU)
 |    +--atof.c (replace atof, convert string to double)
 |    +--atoll.c (replace atoll, convert string to long long int)
 |    +--gmtime_r.c (replace POSIX gmtime_r)
 |    +-- ...
 |
 +--include
 |     +--goalbit
 |     |     +--generic_tools.h (generic queue operations and new vlc list)  
 |     |     +--goalbit_status.h (structure of goalbit status, include quality, goalbit_status_bt_t)
 |     |     +--goalbit_suite_tools.h (get goalbit suits of network)
 |     |     +--gui_tools.h (bt_channel_stats_t, bt_tracker_t, bt_stats_query_t)
 |     |     +--vlc_bitfield.h (bt_bitfield_t)
 |     |     +--vlc_bittorrent.h (goalbitFileParser, bt_Control)
 |     |     +--vlc_broadcaster.h (broadcaster_peer_list)
 |     |     +--vlc_channel_access.h (channel access)
 |     |     +--vlc_crypt.h (crypt events)
 |     |     +--vlc_data.h (data extractor and data injector)
 |     |     +--vlc_kad.h (kademlia descriptor, queries and methods. kad key, value, pair, list ...)
 |     |     +--vlc_upnp.h (upnp)
 |     |     +--vod_tools.h
 |     +--mmx.h (a free MPEG-2 video stream decoder.)
 |     +--vlc (libvlc and mediacontrol)
 |     +--vlc_about.h (auto-generated, GPL, thanks and authors)
 |     +--vlc_access.h (vlc access init)
 |     +--vlc_acl.h (interface to the network Access Control List internal API)
 |     +--vlc_aout.h (audio_output.h: audio output interface)
 |
 +--src
 |   +--audio_output (audio module)
 |   |        +-- ...
 |   +--
 +--modules
 |    +--bittorrent
 |    |      +--bt_client
 |    |      |     +--btTrackerCom
#+END_EXAMPLE
EVENT_TRACKER_COM
p_btc->pf_control
btTrackerCom.m_request_buffer
btTrackerCom.m_reponse_buffer
bt_Control
INTF = interface
pumper_peer
(broadcaster, super_peer, normal_peer, broadcaster_super_peer)

i frame, p frame, b frame.
muxer
channel(tracker, webtracker)
public key & private key

KAD RBT Red Black Tree
* BTFS
1. git clone https://github.com/rkfg/BTFS.git
2. cd BTFS; python btfs.py;
   ImportError: No module named libtorrent
3. http://sourceforge.net/projects/libtorrent/files/py-libtorrent/,
   On freeBSD, you can =sudo pkg install py27-libtorrent-rasterbar=
4. ImportError: No module named fuse
   On freeBSD, =sudo pkg install py27-fusefs=
5. python btfs.py -f follow-stars.torrent -s /home/jolly/Downloads/
   fuse: failed to open fuse device: No such file or directory
   : sudo kldload fuse
   : kldstat
   : python btfs.py -f follow-stars.torrent -s /home/jolly/Downloads/
   fuse: failed to open fuse device: Permission denied
   *Use sysctl to change kernel state*: sudo sysctl "vfs.usermount=1"
   You'll get =vfs.usermount: 0 -> 1=
   In addition, you need join operator group.
   : pw groupmod operator -M jolly
   : id jolly (check whether you have joined operator)
   After relogin, you should run
   : python btfs.py -f follow-stars.torrent -s /home/jolly/Downloads/ ~/btfs
   Then you can play the buffer with mplayer

6. deluge: bittorrent client.

** make torrent
- pkg install gtorrentview
- pkg install mktorrent
  : mktorrent -a http://192.168.109.144/announce -c "local gaoyuanlan.mp4 torrent" -n gaoyuanlan -v -w http://192.168.109.144/gaoyuanlan.mp4 ~/media/gaoyuanlan.mp4 
- start http service
  : sudo service apache24 onestart
  : ln -s gaoyuanlan.mp4 /usr/local/www/apache24/data/
- start btfs
  : python btfs.py -f gaoyuanlan.torrent -s ~/Downloads ~/btfs

* Vshow
1. block size 64 * 1024
2. TrackerClient, Client, Server, PlayerServer
3. Client add parents, add standby peers according to segments.
4. add_todo_jobs, assign_job(schedule algorithm).
5. rank parents according their contribution.
6. TrackerClient sends keep_alive to server.

7. 2014-04-16 read vfs_client.cpp
8. 2014-04-16 read peerFacade module.
9. 2014-04-16 compare FileOp_Linux.cpp with FileOp-Linux.cpp, it seems that the latter is for win32 platform.
10. 2014-04-16 make client, change Makefile (g++ -> clang ++)

11. 2014-04-18 make tracker,
* Sopcast
** experiment: run arm binary on android.
1. Is NDK needed? The NDK is a toolset that allows you to implement parts
   of your app using native-code languages such as C and C++.
2. ./sopclient, I got the answer: permission Denied.
3. =chmod 777 sopclient=, no effect. I found /sdcard is a fat32 fs, so
   chmod does not effect.
4. cp sopclient to /, failed. / is readonly.
5. cp sopclient to /system, run it, success!
** experiment: playback sopcast with terminal
1. su;
2. cd /data/data/org.sopcast.android/files;
3. ./sopclient; you get the help information:
   : ./sp-sc [-T] [-t seconds] [-u username:password] [-n out:total] [-x suffixname] [-a http://auth_url] [-r num] <sop://url> <localport> <playerport>
4. =./sopclient sop://broker.sopcast.com:3912/141796 3908 8908=, 141796 is a American channel.
5. open MxPlayer, play http://127.0.0.1:8908/tv.asf, success!
** search source
** apk
*** experiment 0: run sopclient in APK on android terminal
failed.
** sopcast-player front end
1. self.play_channel call the commond line binary.
** requirement
1. 流媒体服务器源码。（不要源码的话，有软件包应该也可以）。
2. Tracker Server源码。理由：我们需定制服务器日志，做客户群和服务器性能的监控。
3. Peer端的源代码（包括服务模块、请求模块、和Tracker Server交互的模块）。理由：我们需要定制客户端应用，便于客户服务质量的统计分析。
4. 如果存在superPeer, 我们也superPeer的源码。

** experiment:
1. http://192.168.109.174:8080/show
** notes
密码：apecn123456
106.37.212.141
106.37.212.142

* Android
** apk
1. /system 系统目录。
   + app 系统自带的应用程序都在这里。包括apk和odex。ODEX是安卓上的应用程序
     apk中提取出来的可运行文件，即将APK中的classes.dex文件通过dex优化过程将其优化
     生成一个.odex文件单独存放，原APK中的classes.dex文件会保留。这样做可以加快软
     件的启动速度，预先提取，减少对RAM的占用，因为没有odex的话，系统要从apk包中提
     取dex再运行。
   + bin和xbin中都是arm binary, shell命令都在这里。
2. /data user's APP is installed under it.
   - copy the apk to /data/app
   - install the dex in apk to /data/dalvik-cache, such as data@app@org.sopcast.android-1.apk@classes.dex, which is executable to dalvik, it is dalvik byte code.
   - create data directory under /data/data, sopclient is copyed into
     /data/data/org.sopcast.android/files, the shared libaries are copied
     into /data/data/org.sopcast.android/lib.

* popcorn
** try Linux binary release (failed)
1. wget -c http://static.cdnjd.com/releases/popcorn/Popcorn-Time-2.7-Linux-64.tgz
2. mkdir popcorn; cd popcorn;
3. tar xzvf /path/to/Popcorn-Time-2.7-Linux-64.tgz
4. run Popcorn.
   #+BEGIN_EXAMPLE
   $ ./Popcorn-Time 
   ./Popcorn-Time: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./Popcorn-Time)
   ./Popcorn-Time: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./Popcorn-Time)
   ./Popcorn-Time: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./Popcorn-Time)
   #+END_EXAMPLE
   The /lib64/libc.so.6 and /usr/lib64/libstdc++.so.6 exist, but they are a little old.
** DONE try windows binary
   CLOSED: [2014-03-31 Mon 09:03]
1. long long time to connect ...
2. It's OK with vpn
** source
1. grunt: The javascript Task runner
   link: http://gruntjs.com/
2. npm: Node Package Manager
   link: https://www.npmjs.org/
3. javascript: A new variable without `var' will be regarded as a global variable.
4. The core is *peerflix* (https://github.com/mafintosh/peerflix).
5. peerflix uses the streaming torrent engine named *torrent-stream*,
   https://github.com/mafintosh/torrent-stream.git, also created by https://github.com/mafintosh
6. https://github.com/feross/webtorrent, a web version of bittorrent

** peerflix
1. git clone https://github.com/mafintosh/peerflix
2. setup node.js
3. node app.js; if node complains /can not find module xxx/, then =npm install xxx=.

** BT protocol
*** Bencode
1. string [n: xyz...]. For example, =2: at= and =5: Hello=
2. integer, starts with 'i', ends with 'e', for example, =i-10e= represents
   -10, =i23e= represents 23, =i0e= represents 0, but =i-0e= is illegal.
3. list, starts with 'l', ends with 'e', for example: =li10e4:dogse=
   represents [10, "dogs"]; =l5:hellol3:the5:worldee= represents ["hello",
   ["the", "world"]]
4. dict. =d<key><value><key><value>...e=, key must be string, for example
   =d4:name5:jolly3:agei33ee= represents {"name"=> "jolly", "age"=>33}
*** torrent
A torrent file is a dict encoded with /bencode/.
#+BEGIN_EXAMPLE
{
  length: integer,
  md5sum: string (32 chars)
  name: string (file name)
  chunklength: integer (in general, 256KB, 512KB, or 1MB)
  chunks: {
    string (20chars, sha-1 result),
    string (20chars, sha-1 result),
    string (20chars, sha-1 result),
    ... ...
  }
  publish: string (server url)
  date: string (optional)
  comment: string (optional)
  author: string (optional)
}
#+END_EXAMPLE
*** http[s] protocol
Generally BitTorrent Client listen on ports 6881 - 6889.
connections: 30 - 50
*** scrape
Ask server what torrents it is handling.

* DRM on android
** DRM: Digital Rights Management
*** 产业链
DRM是一个不易触及的领域。
由于其安全性高，保密性强，世界上真正掌握DRM核心技术的公司并不多。

DRM产业链中的相关者大概可分为如下三类：

第一类是制定DRM标准的公司或机构，他们掌握DRM的核心技术，对外推广自己的DRM标
准，为需要搭载DRM的公司提供支持。

第二类是数字内容提供商，他们是最迫切应用DRM来保护自己数字版权的人，他们会向
提供标准的公司够买DRM技术，在服务器端加密，并制定数字内容的买卖租赁机制以及
相应的密钥配发原则。

第三类是终端设备制造商，为了让自己的设备具有更广泛的应用性，他们需要搭载主流
的DRM以适应市场需求，在搭载过程中，他们也需要标准公司的支持，拿到一些有专利
的代码包，有时还会与内容提供商合作。当然，还有的时候，一家公司会担当其中的两
个或全部角色，比如亚马逊，他即是内容提供商，提供电子书籍等内容，又是终端设备
商，出品Kindle Fire这样的终端设备，这样做可以让他把内容和终端更好地整合在一
起。

*** DRM标准
+ Open Mobile Alliance推出的OMA DRM
+ Marlin Developer Community提出的Marlin DRM
+ Google则通过收购Widevine公司推出了Widevine DRM。
  Google acquires the Widevine company that provides the DRM support for protecting e.g. the HLS H.264/AAC streams.
  *Need the player support Widevine DRM*.
*** DRM supported by Android
ref: http://blog.csdn.net/innost/article/details/9732847

从Android智能终端来看，Google的原生Android（Android Open Source Project，简称AOSP）系统仅仅集成了OMA DRM V1的一部分功能，它远未构成一个完整的DRM解决方案。
在这种情况下，设备厂商只能根据情况选择合适的DRM解决方案并集成到Android平台中来。
例如，手机厂商可以通过Google的授权以获取Widevine DRM对应的软件包从而将Widevine DRM集成到自己的产品中。

DRM Framework API模块是Framework层暴露给App的接口。该模块中最主要的类是DrmManagerClient。

DRM Framework API模块通过Binder机制和位于drmserver进程（以Android 4.1为例，drmserver的代码位于framework/av/drm/drmserver）中的DRM Manager模块通信。DRM Manager加载并管理系统中所有的DRM插件。

DRM Plugins是真正实现权限管理、数字内容解密等工作的模块。
根据DRM标准的不同，这些Plugins的实现亦不相同。另外，一个手机可能会集成多个DRM Plugin。
这是因为媒体文件如果采用不同的DRM解决方案进行加密的话，手机在播放它们时，DRM Manager需找到对应的DRM Plugin以进行解密。
** How windows Meia Rights Manager Works
** How does Drm10 work?

* MULTIMEDIA
** S/PDIF
Sony/Philips Digital interface
digital sinals transfer specification,
with the SPDIF out of sound card,
some speakers can accept digital signals and convert them to analogue signals and play.
* DONE DRM 10
  CLOSED: [2014-03-31 Mon 09:02]
** Experiment 0: let iis support media string
1. iis can not serve mp4 file.
2. in the iis manager, right click the local computer, add MIME type. you can find mp2 and mp3, but no mp4. add (mp4, video/mpeg). Then you can play the mp4 video with a player.

** Experiment 1: package media with DRM10
1. install IIS 6.0 on windows server 2003
   control panel -> add or remove program -> install windows components
   -> application server
2. start a website service
   control panel -> administration tools -> iis manager
   In the left tree panel, right click on the website node, new website, follow the wizard and click Ok.
   On the new website node, right click, start it immediately.
3. enable ASP extension.
4. copy the samples of WMRM sdk into your www root directory.
5. create seed, public key and private key with VBS.
6. edit global.asa, fill site-url, seed, public key, private key fields.
   *Note:* the site-url do not use `localhost', otherwise the player on
   another machine will request license from localhost, it must fail.
7. enable the global.asa: on the iis manager, right click on the `samples' dir, click `properties', *create*, OK.
   Restart www service: net stop w3svc; net start w3svc.
8. goto http://licenseserver.windowsmedia.com to complete enrollment and to download the latest license server.
   /Note/: you should proceed this step on the windows machine with wmdm sdk installed.
9. access http://localhost/samples/package.asp, package a file.
   If you got a error code: 0xC0042918, it indicates that your file is not a windows media file.
   Windows media formats: Audio(.wav .wma), Video(avi, wm, wmv)
10. If you got a error code: 0xC0042919, that indicates that your file
    format is supported, but the file is bad encoded.
11. If all are Ok, you will see: =status: The media file has been successfully packaged=
12. play the url with /Windows Media Player/, set tools::options, disselect
    播放受保护的内容时自动获取证书, thus when a file is protected, it will
    popup a dialog, waiting for your confrimation to get license.
** Experiment 2: support DRM 10
1. register sopcast.
2. register channel and join a channel group
   id: 151273
   program name: streaming of minds
   channel group
3. play my channel from another machine. If I issue a DRM10 encrypted video, it will try to acquire license.
4. *Conclusion*: sopcast support DRM10.
** Experiment 3: Does android support DRM10?
1. play the url with other players, including the player on android, they
   will try to decode the video directly, playbacking wrong content.
2. *Conclusion*: so they don't support WMRM.

* DONE HLS + AES
** survey
ref:
[[http://www.streamingmedia.com/Articles/Editorial/What-Is-.../What-is-HLS-(HTTP-Live-Streaming)-78221.aspx]]

HLS = Http Live Streaming.
an HTTP-based media streaming communications protocol implemented by Apple Inc.
Apple first announced HLS in 2009.

It works by breaking the overall stream into a sequence of small HTTP-based
file downloads, each download loading one short chunk of an overall
potentially unbounded transport stream.

Though encoded using the /H.264 video codec/ and /AAC/ audio codec, 
audio/video streams must be segmented into chunks in an *MPEG-2 transport stream* with a .ts extension. 

** encryption
*** AES encryption
ref: http://docs.unified-streaming.com/documentation/protect/hls-with-aes.html

The encryption is applied on-the-fly, so there is no preprocessing involved.
Enable: The options for enabling encryptions are stored in the server manifest file.

For HLS AES encryption a content_key (the AES encryption key) and a license
acquisition URL (the location where the player retrieves the key) is
needed.

You can use openssl for generating a random key:
: openssl rand 16 > video.key

The file video.key holds the encryption key that will be requested by the player.

Server Manifest

Next is creating a server manfiest file with enabled encryption.
You need to provide the following options:

1. /hls.content_key/	AES Content Encyption Key (128 bits).
2. /hls.license_server_url/	The URL used by the player to retrieve the key.

#+BEGIN_SRC
mp4split -o video.ism \
  --hls.content_key=`cat video.key | hexdump -e '16/1 "%02x"'` \
  --hls.license_server_url=http://www.example.com/video/video.key \
  video.ismv
#+END_SRC

The generated server manifest file (video.ism) now holds the key
information. When a client requests an .m3u8 playlist the webserver module
will automatically insert the proper #EXT-X-KEY tag and requests for the
MPEG-TS fragments are encrypted on-the-fly.

An example .m3u8 playlist:

#EXTM3U
#EXT-X-VERSION:1
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="http://www.example.com/video/video.key"
#EXTINF:4, no desc
video-audio=65000-video=236000-0.ts

Note that you can add PlayReady and Apple HTTP Live Streaming encryption at
the same time to the server manifest file creation command line. The
following command creates a server manifest file with the key information
embedded:

#+BEGIN_SRC
mp4split -o video.ism \
  --hls.key_seed=000102030405060708090a0b0c0d0e0f \
  --hls.license_server_url=https://www.example.com/oceans.key \
  video.ismv
#+END_SRC

For *Verimatrix VCAS* support, see below for the documentation.
Verimatrix VCAS
USP supports Verimatrix VCAS. To use this you need to use the key_provider and key_provider_url options when creating the server manifest. USP will know how to connect with the Verimatrix server and fetch the keys:

Name	Description
hls.key_provider	The string verimatrix should be used to indicate Verimatrix as a key provider.
hls.key_provider_url	The URL used to retrieve the key.
Example
The following command creates a server manifest file with the key information embedded:

mp4split -o video.ism \
  --hls.key_provider=verimatrix \
  --hls.key_provider_url="http://verimatrix_url/CAB/keyfile?r=MY_ID&t=VOD&c=N" \
  video.ismv
Please note that in the above example some dummy values are used, and that you need to provide values for r, t and c. Please consult the Verimatrix documenttion regarding this. Replaced should be:

the string 'verimatrix_url' should be replaced with the url Verimatrix provides
MY_ID should be replaced with the customer id Verimatrix provides
VOD can also be another type (see the Verimatrix documentation)
N is the number of keys you can fetch, set by Verimatrix
Using SAMPLE-AES (protocol version 5)
For SAMPLE-AES encryption the setup is similar. Please note that this is for on-the-fly encryption. For file based encryption see HLS packaging.

First we have to create a 128-bit CEK (Content Encryption Key) and 128-bit IV (Initialization Vector). This is just a 32 bytes file with random bytes. You could use for example 'openssl' to create the key.

openssl rand 32 > presentation.key
The command-lines for creating the server manifest is similar to the above above, except that we need to use different options.

Option	Description
hls.content_key	The content key used for encryption
hls.license_server_url	The URL where the key can be fetched
hls.playout	The string identifier ('sample_aes')
Example
#!/bin/bash

CONTENT_KEY=A8FD3449772FA3DD2F1BCE74764A8B46

MP4SPLIT_OPTIONS=
MP4SPLIT_OPTIONS+="--hls.content_key=$CONTENT_KEY "
MP4SPLIT_OPTIONS+="--hls.license_server_url=http://example.com/oceans_drm.key "
MP4SPLIT_OPTIONS+="--hls.no_discontinuities "
MP4SPLIT_OPTIONS+="--hls.playout=sample_aes "

mp4split -o example.ism $MP4SPLIT_OPTIONS oceans-64k.ismv oceans-250k.ismv

HLS also specifies a standard encryption mechanism using AES and a method
of secure key distribution using HTTPS with either a device specific realm
login or HTTP cookie which together provide a simple DRM system.
*** practice
yum install openssl
: openssl rand 16 > video.key
get mp4split command line tool
Download the source of the H264 Streaming Module for Lighttpd.

For Lighttpd 1.4.18:

cd ~
wget http://h264.code-shop.com/download/lighttpd-1.4.18_mod_h264_streaming-2.2.0.tar.gz
tar -zxvf lighttpd-1.4.18_mod_h264_streaming-2.2.0.tar.gz
For Lighttpd 1.5.0:

cd ~
wget http://h264.code-shop.com/download/lighttpd-1.5.0_mod_h264_streaming-2.2.0.tar.gz
tar -zxvf lighttpd-1.5.0_mod_h264_streaming-2.2.0.tar.gz
If you plan to play Multi Bit Rate H.264 encoded videos, you will also need the command line tool 'mp4split' to create the Smooth Streaming manifest files.

wget http://h264.code-shop.com/download/mp4split-2.2.0.tar.gz
tar -zxvf mp4split-2.2.0.tar.gz

server manifest

ismv = ISMV file is an IIS Smooth Streaming Video. 
ism = IIS Smooth Streaming Server Manifest Data

Try apache multimedia serve
upload a mp4 file
download psftp.exe
> open 192.168.109.50
user: root; passwd: 123456
> cd /home/aptv
> lcd e:/jollywing/documents
> put gaoyuanlan.mp4
> bye

start httpd: /etc/init.d/httpd start
try http://192.168.109.50/gaoyuanlan.mp4

`cat video.key | hexdump -e '16/1 "%02x"'` \

mp4split -o video.ism \
  --hls.content_key=`cat video.key | hexdump -e '16/1 "%02x"'` \
  --hls.license_server_url=http://www.example.com/video/video.key \
  video.ismv

*** 防下载
动态生成m3u8以及ts切片的地址，在下发到终端之后一定时间内，或下次请求时，改变生成的路径。
目前所有用HTTP实现视频点播的网站，如果有版权保护（防下载）都是用的这种方法。

*** session encryption
访问接口要有apikey才能取回m3u8的地址和生成session,然后用带session的m3u8里的
ts地址去访问具体的ts切片的服务器，ts切片上也带session

** Content Protection/Closed Captions in HLS
HLS doesn’t natively support digital rights management (DRM) though you
can encrypt the data and provide key access using HTTPS authentication.
There are several third-party DRM solutions becoming available, including
from (1) AuthenTec, (2) SecureMedia, and (3) WideVine. HLS can support
closed captions included in the MPEG-2 transport stream.

** HTTP Live Streaming client
Apple recommends using the HTML5 video tag for deploying HLS video on a website.

** TODO android play encrypted hls?
1. according to http://stackoverflow.com/questions/14235148/how-to-decrypt-ts-files-given-in-a-m3u8-file/14235534#14235534
   the media framework of android can encrypted hls automatically.
   =As mentioned in my comment, AES-128 decyption is done automatically on Android 3.x & 4.x devices by the mediaframework.=

   Below a quote from the HLS draft

   EXTINF is a record marker that describes the media file identified by the
   URI that follows it. Each media file URI MUST be preceded by an EXTINF tag.

2. split mp4 ts.

   : useradd -m -U jolly; passwd jolly; 567890

   install ffmpeg:

   #+BEGIN_SRC sh
   wget -c http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
   tar xjvf ffmpeg-snapshot.tar.bz2
   cd ffmpeg
   ./configure --disable-yasm
   make
   sudo make install
   #+END_SRC

   : ffmpeg -i gaoyuanlan.mp4 -codec copy -vbsf h264_mp4toannexb -map 0 -f segment -segment_list out.m3u8 -segment_time 10 out%03d.ts

3. Test HLS.
   mplayer http://192.168.109.50/aes-demo/gaoyuanlan.mp4 OK
   mplayer http://192.168.109.50/aes-demo/out.m3u8 NOT WORK.
   vlc http://192.168.109.50/aes-demo/out.m3u8 OK.

4. encryption with aes-128

   openssl encryption:
   http://stackoverflow.com/questions/3010638/using-openssl-encryption-for-apples-http-live-streaming

   #+BEGIN_SRC sh
   #!/bin/bash
   keyfile="video.key"
   openssl rand 16 > $keyfile
   hexKey=`cat $keyfile | hexdump -e '16/1 "%02x"'`
   echo $hexKey
   hexIV='0'
   
   for seg in $(ls *.ts)
   do
   echo "Encrypting $seg ..."
   base="$(basename $seg .ts)"
   out="${base}-encrypted.ts"
   openssl aes-128-cbc -e -in $seg -out $out -p -nosalt -iv ${hexIV}  -K ${hexKey}
   echo "Create $out."
   done
   #+END_SRC

   add encrypt hint to m3u8
   : #EXT-X-KEY:METHOD=AES-128,URI="video.key"
   before
   : #EXTINF:10...

   A script for create keys for each ts:
   #+BEGIN_SRC
   #!/bin/bash
   
   for seg in $(ls *.ts)
   do
   echo "Encrypting $seg ..."
   base="$(basename $seg .ts)"
   keyfile="${base}.key"
   openssl rand 16 > $keyfile
   hexKey=`cat $keyfile | hexdump -e '16/1 "%02x"'`
   hexIV='0'
   echo "hexKey: ${hexKey}"
   out="${base}-encrypted.ts"
   openssl aes-128-cbc -e -in $seg -out $out -p -nosalt -iv ${hexIV}  -K ${hexKey}
   echo "Create $out."
   done
   #+END_SRC

5. Test.
   Apple sarafi, OK.
   Android MxPlayer: http://192.168.1.50/aes-demo/encrypt.m3u8

6. check log of apache
   : cd /var/log/httpd
   : vim aptv-access.log

* DONE BaiDu KanKan
  CLOSED: [2014-03-20]
kankan.baidu.com
小度i耳目
产品：摄象头 + android app.
It costs 600+
看孩子，看宠物。

