* 整理是一切的开始
来自豆瓣的读书笔记

关注时间管理已久，但一直都是看一些经验文章，琐碎也不够系统。这一篇是荒河莱美的《整理是一切的开始》的个人读书笔记，也为想要接触和学习时间管理和整理术却依旧没有时间看书的朋友提供一个参考。
一开始想看这本书的时候，是被封皮的一个小测试吸引，一共六个选项，勾选跟自己情况相符合的选项，得分1~3分的，建议将本书作为参考书阅读；得分3~5，建议当做教科书阅读；超过5分的当做救命书阅读吧！测试如下：
          办公桌一篇凌乱，永远有一样东西怎么也找不到
         抽屉里躺着N张会员卡，拿出来用时才发现已经过期一年了
         紧赶慢赶还是赶不上deadline,常常要红着脸跟人家道歉
         拼死拼活忙了一整天，却搞不清楚时间究竟都花在了哪里
         到处交换名片，回来放在名片夹里就再也想不起来谁是谁了
         不会说NO，把别人的事当自己的事，做惯了老好人
做完测试一定会有人在庆幸自己得分很低或者根本没有以上的所有情况，当我初读的时候也的确，我只满足这个测试的一两个选项。但做完测试倒是启发了我想起我个人的一些问题，有时候累积的一堆todo，打起精神在星期六的早上准备花一整天把他们全部解决掉的时候，我看着我乱七八糟的书桌就动力大减，于是又花了一个上午收拾我的书桌，在这个过程中，无意中发现以前没看完的书就会停下来看书，所以真正有时间做“正事”的时候，已经是晚上了，熬夜又不可避免。
想到这些，我且把这本书当做救命书阅读吧。
全书讲的主要是三个方面：物品整理、时间管理、和人际关系的管理。作者在前言推荐内容选看，再者这本书的作者是日本人，所以会有些习惯与我们不同，再者因为各行各界各年龄段的生活重心不同，有些并不实用。以下我归纳整理出了有价值的重点，便于打印出来随时提醒自己。
——————————————————————————————————————
第一章  物品整理，东西越少，我们的效率越高。
荒野莱美在书里提到，如果我们周围一直杂乱无章，我们的起点就像是一个负数，当然落后于那些从零开始的人。
1.清空环境：	
        把东西分为需要、不需要和不知道需不需要，分开处理；
	为不知道的东西贴上便签，写上日期，一周之后依然没动就果断捐去慈善机构吧；
	控制收纳工具的数量；
2.清空大脑：
	需要做的事放在最显眼的地方提醒自己（比如书本），拖延自己的束之高阁；
	物品放在定好的相应的位置上，对号入座，用完放回；
	没用过的东西开发新的利用价值，实在没用就放弃吧；
	让书架抽屉永远空出1/3的空间；
3.建议放弃的物品：	
        根本不喜欢，用着没有好心情的东西
	可以被替换的东西（笔记本，笔，水杯等）
	有损身体健康的东西（硌脚的鞋，昏暗的灯等）
	难收纳的东西（屋里早就过时且布满灰尘的装饰品）
	阻碍自己向上的东西（游戏机之类的）
————————————————————————————————————
第二章 时间整理，清楚你每天在干什么
自己花一个小时认真想一下自己的时间分化，墙裂建议写下来！好好反省一下浪费的时间，规划空闲的时间，好好利用自己最有效率的时间。
1.“把一天分成24份“：
	提前准备，主动提出建议选项，不在讨论中浪费时间。
	不能保证完成时间的事件如开会，不放在效率高的上午来做。
	改变一下生活模式，说不定更有收获。
	留出应急时间
	物品整理配合时间整理，不在找东西上浪费时间
	脑子想想琐碎的事情，争取合并完成
	起早比熬夜更有用
2.建议放弃的时间：
	漫无目的的时间
	不利于健康的时间
	浪费别人的时间
	零碎的时间（等人之类）
	12点之后的时间
__________________________________________________________________
第三章 人际关系整理，有些人脉是用来放弃的
翻开名片或手机通讯录，删除打算放弃的关系，激活有用的关系     
1.选择人脉：
	减少交往人数，加深有用的交往关系
	决定”跟谁多长时间见一次面“，优先选择与自己有相同价值观的
	相应的事情和相应的朋友做
	尽量不要公私混同
	不必特别刻意拓展自己的人脉，充实自己，培养自己的钝感力（推荐渡边淳一的《钝感力》一书）。不要因为没用的人脉，忽略对自己更重要的人脉
2.复苏人脉：
	主动邀请，AA制可以减轻对方的负担，事先计划好时间和费用，留出备用时间
	只有双赢才能维持良好的关系，能为别人提供”利益“的人更好，所以要清楚自己价值，提升自己的价值。
	考虑人脉顺序，不要越级
3.建议放弃的关系：
	偏执、怨恨、毒舌的人
	大大咧咧的人
	出于道义保持交往的人
	多次邀请没有回应的人
	没有交集的人
如果常常生活在阴郁消极的生活环境或人际环境里，我们都很难发挥应有的创造力和生产力。而走出这些消极因素的方法，可能就是你花一个上午整理好你的房间，自己做一张计划表列好近期的计划和预计完成时间或拒绝一次消极人脉的邀请，当然这一切都建立在行动力上，没有行动力，怎样的整理技巧都无法把你从电脑屏幕前移开。

读书笔记2
http://blog.sina.com.cn/s/blog_49fbfad50102e04k.html


关于物品的整理
只有清空了桌面，才能看清楚什么是真正需要的东西。 
家中使用的物品仅限于可以放进收纳工具的，放不下的就尽快处理掉。 
在常用的东西上贴上便签纸，没有贴便签纸的东西就是不需要的东西，一定要坚决处理掉。 
试着每天放弃一件东西。坚持下去，你就会养成不堆积东西的习惯。 
准备一个“犹豫袋”。整理东西时如果犹豫不决，就先把它们放进“犹豫袋”。 
确定常用物品的摆放位置，让物品对号入座。 
重新考虑没用过东西的使用方式和摆放位置。 
放置很久的东西是否已经落伍，市面上还有哪些新产品？ 
处理掉过去喜欢的东西，把精力集中到现在感兴趣的事上。 
实在不想仍的东西，可以找其它东西代替。 
处理掉不需要的东西，让书架、抽屉等永远空出1／3的空间。 
东西越多，居住空间越小、越被动、被占用的时间越多。 
你必须立即放弃的5种物品(1)毫无幸福感 (2)可代替 (3)有损健康 (4)难以收纳 (5)阻碍自己向上 


关于时间的整理
准备好便签纸。一张便签纸代表一小时，来了解自己时间使用情况。 
事先定好星期几与人见面，有人约见时，先从这段时间里挑选。 
不要在上午开会，上午是效率最高的时间段，最好集中精力做自己的工作。 
需要拜访客户时，提前一小时到达然后在附近工作一小时。 
找到适合自己的最佳时间组合 
把星期三空出来，作为应对各种突发事件的备用日。 
确认3天后的预定，为自己准备时间整理袋，将不同工作放在不同的袋子里。 
把琐碎的工作放到一起去执行。 
考虑和自己一起工作的人，不要占用别人的时间。 
星期五晚上不要熬夜，星期六可以享受一天的美好时光。 
你必须立即放弃的5种时间 (1)与成长无关的 (2)对健康无益的 (3)浪费他人时间 (4)零碎时间 (5)夜里12点以后的时间 


关于人际关系的整理
重新整理一遍自己的人际关系。决定打算放弃的关系、翻出长久以来被忽略的关系。 
意识到自己和对方的共同点，让自己的目的与交往的对象相符。 
决定“跟谁多长时间见一面”。优先选择与自己拥有共同价值观的人。 
不要将工作关系与私人关系混为一谈。 
不用参加跨行业交流会。可以参加自己感兴趣的演讲会或学习会。 
远离朋友聚会、可有可无的邮件来往、微博和社交网。 
让人脉复苏的邀请方式 (1)告知对方地点和预算 (2)建议AA制 (3)为对方准备三个可以选择的日期。 
与人见面时，带上对对方有利的“礼物”（信息或利益）。 
收到邮件要立刻回复。如无法立即回答邮件的问题，至少让对方知道你收到了邮件。 
工作中，任何行动都要考虑人脉顺序。 
你必须立即放弃的5种人际关系 (1)偏执、怨恨、毒蛇的人 (2)大咧咧的人 (3)出于道义、感激而与之保持交往的人(4)邀请3次不肯应邀的人  (5)没有交往的人 


