#+TITLE:FreeBSD notes

* Install
** install the base system.
1. burn the freebsd 10 iso to cd. (The open source buring tool *InfraRecorder* is suggested.)
2. reboot your computer with the cdrom.
3. Press "Enter" to startup the default multi-user session.
4. select "Install".
5. Manual partition. If you has MBR partition table on your harddisk. 
   You should create a /freebsd/ partition with the freespace,
   then create freebsd-ufs, freebsd-swap in the freebsd partition.
   We call them slices. Make sure there is a mountpoint ~/~.
6. You can use grub of Linux to boot FreeBSD, add the following lines to /menu.lst/.
   #+BEGIN_EXAMPLE
   title freebsd
   rootnoverify (hd0, x)
   chainloader +
   #+END_EXAMPLE
** install pkgs
*** pkg
pkgng (ng = next generation) is the next generation replacement for the
traditional FreeBSD package management tools.
: # /usr/sbin/pkg
will download and install /pkgng/.

: # pkg2ng
convert the old pkg format.

The default package repository location is defined in /usr/local/etc/pkg.conf or by the PACKAGESITE environment variable

run =pkg= to see help info.

Usage information for pkgng is available in pkg(8) or by running pkg without additional arguments.
: # pkg help install
OR
: # man pkg-install
: # pkg update

pkg stats, list how many packages installed.

=pkg query '%Fp' <pkgname>= list all installed files of <pkgname>

: pkg rquery %c <pkgname>
Even though you did not install the pkg, you can check its comment with this.

* Shell
The default shell is tcsh on freeBSD.
When you login, tcsh will read ~/.login.
Each time you startup a tcsh, tcsh will read ~/.tcshrc
When you logout, tcsh will read ~/.logout.
The global files are: /etc/csh.login, /etc/csh.logout, /etc/csh.cshrc.

If you use sh OR ksh as your shell, it will read ~/.profile.

If you use bash, it will find ~/.bash_profile, ~/.bash_login, ~/.profile,
If it found one of them, it will take that file as its profile.
* Account
*nobody* is the generic unprivileged system account. 
: # adduser
Press Enter, then add an user interactively.

Check which users contained in a group.
: pw groupshow wheel

add a user to  a group:
: pw groupmod operator -M jolly
: id jolly
You'll see jolly has joined operator group.
* Chroot
chroot = Change Root; change the root dir referred by a program. The original root dir is '/'.
If you has two unix/Linux installed, you can mount the root region of another system,
and =chroot $ANOTHER_SYS_ROOT /bin/bash=

* network
** DHCP
add
: ifconfig_dc0="DHCP"
to ~/etc/rc.conf~.

** static
add
: ifconfig_dc0="inet 192.168.1.3 netmask 255.255.255.0"
: defaultrouter="192.168.1.1"
to ~/etc/rc.conf~

add
: nameserver 192.168.110.109
to  ~/etc/resolv.conf~

then
: service netif restart

* Kernel
1. Change and check kernel state: =sysctl=
   SET: ~sysctl vfs.usermount=1~
   CHECK: ~sysctl vfs.usermount~
* Module
Edit /boot/loader.conf, put xxx_load="YES" to enable xxx loaded on boot.
For example, to enable fuse on boot, add fuse_load="YES" on boot.
* XWindow

#+BEGIN_EXAMPLE
pkg install xorg
pkg install icewm
pkg install xinit
echo 'exec icewm-session' > .xinitrc
startx
#+END_EXAMPLE

mouse or keyboard not work?
pkg install xf86-input-mouse
pkg install xf86-input-keyboard

* locale
: locale -a
list all supported locales

: locale
check the current locale

* hardware
* sudo
su: sorry
# pw usermod jolly -g wheel
only the users who belongs wheel group can execute `su'

sudo
pkg install sudo
: # visudo
uncomment the `%wheel ALL=(ALL) NOPASSWD: ALL'

* at
at: you do not have permission to use this program
check for /var/at.allow, then check /var/at.deny
sudo touch /var/at/at.deny
you can use at

sudo service atd start
atd does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d)
*** ports
The Ports Collection is a set of Makefiles, patches, and description files stored in /usr/ports.
: portsnap fetch
: portsnap extract
: portsnap update

pkg install xorg-server
pkg install icewm
pkg install xinit
startx

pkg install xf86-input-mouse xf86-input-keyboard

* advanced
=man re-format=, check the syntax of regular expressions.
